const ArrayDummyData = {
  Tittle: [
    { SalutationCode: 2, SalutationName: "Mr." },
    { SalutationCode: 3, SalutationName: "Mrs." },
    { SalutationCode: 4, SalutationName: "Ms." },
    { SalutationCode: 5, SalutationName: "Dr." },
    { SalutationCode: 6, SalutationName: "Capt." },
    { SalutationCode: 11, SalutationName: "Miss." },
    { SalutationCode: 8, SalutationName: "Mx." },
  ],
  GenderData: [
    { GenderCode: 1, GenderName: "Male" },
    { GenderCode: 2, GenderName: "Female" },
    { GenderCode: 3, GenderName: "Prefer not to disclose" },
    { GenderCode: 7, GenderName: "Trans Male" },
    { GenderCode: 8, GenderName: "Trans Female" },
    { GenderCode: 9, GenderName: "3Gender" },
  ],
  CountryData: [
    { CountryCode: "1", CountryName: "India" },
    { CountryCode: "2", CountryName: "United States of America" },
    { CountryCode: "3", CountryName: "China" },
    { CountryCode: "6", CountryName: "Russian Federation" },
    { CountryCode: "11", CountryName: "Afghanistan" },
    { CountryCode: "12", CountryName: "Albania" },
    { CountryCode: "13", CountryName: "Algeria" },
    { CountryCode: "14", CountryName: "American Samoa" },
    { CountryCode: "15", CountryName: "Andorra" },
    { CountryCode: "16", CountryName: "Angola" },
    { CountryCode: "17", CountryName: "Anguilla" },
    { CountryCode: "18", CountryName: "Antigua and Barbuda" },
    { CountryCode: "19", CountryName: "Argentina" },
    { CountryCode: "20", CountryName: "Armenia" },
    { CountryCode: "21", CountryName: "Aruba" },
    { CountryCode: "22", CountryName: "Australia" },
    { CountryCode: "23", CountryName: "Austria" },
    { CountryCode: "24", CountryName: "Azerbaijan" },
    { CountryCode: "25", CountryName: "Bahamas" },
    { CountryCode: "26", CountryName: "Bahrain" },
    { CountryCode: "27", CountryName: "Bangladesh" },
    { CountryCode: "28", CountryName: "Barbados" },
    { CountryCode: "29", CountryName: "Belarus" },
    { CountryCode: "30", CountryName: "Belgium" },
    { CountryCode: "31", CountryName: "Belize" },
    { CountryCode: "32", CountryName: "Benin" },
    { CountryCode: "33", CountryName: "Bermuda" },
    { CountryCode: "34", CountryName: "Bhutan" },
    { CountryCode: "35", CountryName: "Bolivia" },
    { CountryCode: "36", CountryName: "Bosnia and Herzegovina" },
    { CountryCode: "37", CountryName: "Botswana" },
    { CountryCode: "38", CountryName: "Brazil" },
    { CountryCode: "39", CountryName: "British Virgin Islands" },
    { CountryCode: "40", CountryName: "Brunei Darussalam" },
    { CountryCode: "41", CountryName: "Bulgaria" },
    { CountryCode: "42", CountryName: "Burkina Faso" },
    { CountryCode: "43", CountryName: "Burundi" },
    { CountryCode: "44", CountryName: "Cambodia" },
    { CountryCode: "45", CountryName: "Cameroon" },
    { CountryCode: "46", CountryName: "Canada" },
    { CountryCode: "47", CountryName: "Cape Verde Islands" },
    { CountryCode: "48", CountryName: "Cayman Islands" },
    { CountryCode: "49", CountryName: "Central African Republic" },
    { CountryCode: "50", CountryName: "Chad" },
    { CountryCode: "52", CountryName: "Chile" },
    { CountryCode: "55", CountryName: "Colombia" },
    { CountryCode: "56", CountryName: "Comoros" },
    { CountryCode: "57", CountryName: "Congo" },
    { CountryCode: "58", CountryName: "Cook Islands" },
    { CountryCode: "59", CountryName: "Costa Rica" },
    { CountryCode: "60", CountryName: "Cote d'Ivoire" },
    { CountryCode: "61", CountryName: "Croatia" },
    { CountryCode: "62", CountryName: "Cuba" },
    { CountryCode: "63", CountryName: "Cyprus" },
    { CountryCode: "64", CountryName: "Czech Republic" },
    { CountryCode: "67", CountryName: "Denmark" },
    { CountryCode: "68", CountryName: "Djibouti" },
    { CountryCode: "69", CountryName: "Dominica" },
    { CountryCode: "70", CountryName: "Dominican Republic" },
    { CountryCode: "71", CountryName: "Ecuador" },
    { CountryCode: "72", CountryName: "Egypt" },
    { CountryCode: "73", CountryName: "El Salvador" },
    { CountryCode: "74", CountryName: "Equatorial Guinea" },
    { CountryCode: "75", CountryName: "Eritrea" },
    { CountryCode: "76", CountryName: "Estonia" },
    { CountryCode: "77", CountryName: "Ethiopia" },
    { CountryCode: "78", CountryName: "Faeroe Islands" },
    { CountryCode: "79", CountryName: "Falkland Islands (Malvinas)" },
    { CountryCode: "81", CountryName: "Finland" },
    { CountryCode: "82", CountryName: "France" },
    { CountryCode: "83", CountryName: "French Guiana" },
    { CountryCode: "84", CountryName: "French Polynesia" },
    { CountryCode: "85", CountryName: "Gabon" },
    { CountryCode: "86", CountryName: "Gambia" },
    { CountryCode: "87", CountryName: "Georgia" },
    { CountryCode: "88", CountryName: "Germany" },
    { CountryCode: "89", CountryName: "Ghana" },
    { CountryCode: "90", CountryName: "Gibraltar" },
    { CountryCode: "91", CountryName: "Greece" },
    { CountryCode: "92", CountryName: "Greenland" },
    { CountryCode: "93", CountryName: "Grenada" },
    { CountryCode: "94", CountryName: "Guadeloupe" },
    { CountryCode: "95", CountryName: "Guam" },
    { CountryCode: "96", CountryName: "Guatemala" },
    { CountryCode: "97", CountryName: "Guinea" },
    { CountryCode: "98", CountryName: "Guinea-Bissau" },
    { CountryCode: "99", CountryName: "Guyana" },
    { CountryCode: "100", CountryName: "Haiti" },
    { CountryCode: "102", CountryName: "Honduras" },
    { CountryCode: "103", CountryName: "Hungary" },
    { CountryCode: "104", CountryName: "Iceland" },
    { CountryCode: "105", CountryName: "Indonesia" },
    { CountryCode: "106", CountryName: "Iran (Islamic Republic of)" },
    { CountryCode: "107", CountryName: "Iraq" },
    { CountryCode: "108", CountryName: "Ireland" },
    { CountryCode: "109", CountryName: "Isle of Man" },
    { CountryCode: "110", CountryName: "Israel" },
    { CountryCode: "111", CountryName: "Italy" },
    { CountryCode: "112", CountryName: "Jamaica" },
    { CountryCode: "113", CountryName: "Japan" },
    { CountryCode: "114", CountryName: "Jordan" },
    { CountryCode: "115", CountryName: "Kazakhstan" },
    { CountryCode: "116", CountryName: "Kenya" },
    { CountryCode: "117", CountryName: "Kiribati" },
    { CountryCode: "118", CountryName: "Kuwait" },
    { CountryCode: "119", CountryName: "Kyrgyzstan" },
    { CountryCode: "120", CountryName: "Lao People's Democratic Republic" },
    { CountryCode: "121", CountryName: "Latvia" },
    { CountryCode: "122", CountryName: "Lebanon" },
    { CountryCode: "123", CountryName: "Lesotho" },
    { CountryCode: "124", CountryName: "Liberia" },
    { CountryCode: "125", CountryName: "Libyan Arab Jamahiriya" },
    { CountryCode: "126", CountryName: "Liechtenstein" },
    { CountryCode: "127", CountryName: "Lithuania" },
    { CountryCode: "128", CountryName: "Luxembourg" },
    { CountryCode: "129", CountryName: "Madagascar" },
    { CountryCode: "130", CountryName: "Malawi" },
    { CountryCode: "131", CountryName: "Malaysia" },
    { CountryCode: "132", CountryName: "Maldives" },
    { CountryCode: "133", CountryName: "Mali" },
    { CountryCode: "134", CountryName: "Malta" },
    { CountryCode: "135", CountryName: "Marshall Islands" },
    { CountryCode: "136", CountryName: "Martinique" },
    { CountryCode: "137", CountryName: "Mauritania" },
    { CountryCode: "138", CountryName: "Mauritius" },
    { CountryCode: "139", CountryName: "Mayotte" },
    { CountryCode: "140", CountryName: "Mexico" },
    { CountryCode: "141", CountryName: "Micronesia (Fed. States of)" },
    { CountryCode: "142", CountryName: "Monaco" },
    { CountryCode: "143", CountryName: "Mongolia" },
    { CountryCode: "144", CountryName: "Montenegro" },
    { CountryCode: "145", CountryName: "Montserrat" },
    { CountryCode: "146", CountryName: "Morocco" },
    { CountryCode: "147", CountryName: "Mozambique" },
    { CountryCode: "148", CountryName: "Myanmar" },
    { CountryCode: "149", CountryName: "Namibia" },
    { CountryCode: "150", CountryName: "Nauru" },
    { CountryCode: "151", CountryName: "Nepal" },
    { CountryCode: "152", CountryName: "Netherlands" },
    { CountryCode: "153", CountryName: "Netherlands Antilles" },
    { CountryCode: "154", CountryName: "New Caledonia" },
    { CountryCode: "155", CountryName: "New Zealand" },
    { CountryCode: "156", CountryName: "Nicaragua" },
    { CountryCode: "157", CountryName: "Niger" },
    { CountryCode: "158", CountryName: "Nigeria" },
    { CountryCode: "159", CountryName: "Niue" },
    { CountryCode: "160", CountryName: "Norfolk Island" },
    { CountryCode: "161", CountryName: "North Korea" },
    { CountryCode: "162", CountryName: "North Macedonia" },
    { CountryCode: "163", CountryName: "Northern Mariana Islands" },
    { CountryCode: "164", CountryName: "Norway" },
    { CountryCode: "165", CountryName: "Oman" },
    { CountryCode: "166", CountryName: "Pakistan" },
    { CountryCode: "167", CountryName: "Palau" },
    { CountryCode: "168", CountryName: "Palestine" },
    { CountryCode: "169", CountryName: "Panama" },
    { CountryCode: "170", CountryName: "Papua New Guinea" },
    { CountryCode: "171", CountryName: "Paraguay" },
    { CountryCode: "172", CountryName: "Peru" },
    { CountryCode: "173", CountryName: "Philippines" },
    { CountryCode: "174", CountryName: "Pitcairn Islands" },
    { CountryCode: "175", CountryName: "Poland" },
    { CountryCode: "176", CountryName: "Portugal" },
    { CountryCode: "177", CountryName: "Puerto Rico" },
    { CountryCode: "178", CountryName: "Qatar" },
    { CountryCode: "179", CountryName: "Republic of Korea" },
    { CountryCode: "180", CountryName: "Republic of Moldova" },
    { CountryCode: "181", CountryName: "Réunion" },
    { CountryCode: "182", CountryName: "Romania" },
    { CountryCode: "183", CountryName: "Rwanda" },
    { CountryCode: "184", CountryName: "Saint Kitts and Nevis" },
    { CountryCode: "185", CountryName: "Saint Lucia" },
    { CountryCode: "186", CountryName: "Saint Vincent and the Grenadines" },
    { CountryCode: "187", CountryName: "Samoa" },
    { CountryCode: "188", CountryName: "San Marino" },
    { CountryCode: "189", CountryName: "Sao Tome and Principe" },
    { CountryCode: "190", CountryName: "Saudi Arabia" },
    { CountryCode: "191", CountryName: "Senegal" },
    { CountryCode: "192", CountryName: "Serbia" },
    { CountryCode: "193", CountryName: "Seychelles" },
    { CountryCode: "194", CountryName: "Sierra Leone" },
    { CountryCode: "195", CountryName: "Singapore" },
    { CountryCode: "196", CountryName: "Slovakia" },
    { CountryCode: "197", CountryName: "Slovenia" },
    { CountryCode: "198", CountryName: "Solomon Islands" },
    { CountryCode: "199", CountryName: "Somalia" },
    { CountryCode: "200", CountryName: "South Africa" },
    { CountryCode: "201", CountryName: "South Sudan" },
    { CountryCode: "202", CountryName: "Spain" },
    { CountryCode: "203", CountryName: "Sri Lanka" },
    { CountryCode: "204", CountryName: "Sudan" },
    { CountryCode: "205", CountryName: "Suriname" },
    { CountryCode: "206", CountryName: "Swaziland" },
    { CountryCode: "207", CountryName: "Sweden" },
    { CountryCode: "208", CountryName: "Switzerland" },
    { CountryCode: "209", CountryName: "Syrian Arab Republic" },
    { CountryCode: "210", CountryName: "Tajikistan" },
    { CountryCode: "211", CountryName: "Tanzania, United Republic of" },
    { CountryCode: "212", CountryName: "Thailand" },
    { CountryCode: "213", CountryName: "Timor-Leste" },
    { CountryCode: "214", CountryName: "Togo" },
    { CountryCode: "215", CountryName: "Tokelau" },
    { CountryCode: "216", CountryName: "Tonga" },
    { CountryCode: "217", CountryName: "Trinidad and Tobago" },
    { CountryCode: "218", CountryName: "Tunisia" },
    { CountryCode: "219", CountryName: "Turkey" },
    { CountryCode: "220", CountryName: "Turkmenistan" },
    { CountryCode: "221", CountryName: "Turks and Caicos Islands" },
    { CountryCode: "222", CountryName: "Tuvalu" },
    { CountryCode: "223", CountryName: "Uganda" },
    { CountryCode: "224", CountryName: "Ukraine" },
    { CountryCode: "225", CountryName: "United Arab Emirates" },
    { CountryCode: "226", CountryName: "United Kingdom" },
    { CountryCode: "228", CountryName: "Uruguay" },
    { CountryCode: "229", CountryName: "Uzbekistan" },
    { CountryCode: "230", CountryName: "Vanuatu" },
    { CountryCode: "231", CountryName: "Venezuela" },
    { CountryCode: "232", CountryName: "Viet Nam" },
    { CountryCode: "233", CountryName: "Western Sahara" },
    { CountryCode: "234", CountryName: "Yemen" },
    { CountryCode: "235", CountryName: "Zambia" },
    { CountryCode: "236", CountryName: "Zimbabwe" },
  ],
  StateData: [
    { StateCode: "28", StateName: "Andhra Pradesh" },
    { StateCode: "12", StateName: "Arunachal Pradesh" },
    { StateCode: "18", StateName: "Assam" },
    { StateCode: "85", StateName: "Bhutan" },
    { StateCode: "10", StateName: "Bihar" },
    { StateCode: "4", StateName: "Chandigarh" },
    { StateCode: "22", StateName: "Chattisgarh" },
    { StateCode: "26", StateName: "Dadra & Nagar Haveli" },
    { StateCode: "25", StateName: "Daman & Diu" },
    { StateCode: "7", StateName: "Delhi" },
    { StateCode: "30", StateName: "Goa" },
    { StateCode: "24", StateName: "Gujarat" },
    { StateCode: "6", StateName: "Haryana" },
    { StateCode: "2", StateName: "Himachal Pradesh" },
    { StateCode: "1", StateName: "Jammu & Kashmir" },
    { StateCode: "20", StateName: "Jharkhand" },
    { StateCode: "29", StateName: "Karnataka" },
    { StateCode: "32", StateName: "Kerala" },
    { StateCode: "31", StateName: "Lakshadweep" },
    { StateCode: "23", StateName: "Madhya Pradesh" },
    { StateCode: "27", StateName: "Maharashtra" },
    { StateCode: "14", StateName: "Manipur" },
    { StateCode: "17", StateName: "Meghalaya" },
    { StateCode: "15", StateName: "Mizoram" },
    { StateCode: "13", StateName: "Nagaland" },
    { StateCode: "50", StateName: "Nct" },
    { StateCode: "21", StateName: "Odisha" },
    { StateCode: "34", StateName: "Pondicherry" },
    { StateCode: "3", StateName: "Punjab" },
    { StateCode: "8", StateName: "Rajasthan" },
    { StateCode: "11", StateName: "Sikkim" },
    { StateCode: "33", StateName: "Tamil Nadu" },
    { StateCode: "53", StateName: "Telangana" },
    { StateCode: "16", StateName: "Tripura" },
    { StateCode: "9", StateName: "Uttar Pradesh" },
    { StateCode: "49", StateName: "Uttarakhand" },
    { StateCode: "5", StateName: "Uttaranchal" },
    { StateCode: "60", StateName: "V2s" },
    { StateCode: "19", StateName: "West Bengal" },
  ],
  MotherTongueData: [
    { MothertoungeCode: "259", MotherTongueName: "Angami" },
    { MothertoungeCode: "160", MotherTongueName: "Assamese" },
    { MothertoungeCode: "253", MotherTongueName: "Badaga" },
    { MothertoungeCode: "161", MotherTongueName: "Bengali" },
    { MothertoungeCode: "162", MotherTongueName: "Bhojpuri" },
    { MothertoungeCode: "163", MotherTongueName: "Bhutanese" },
    { MothertoungeCode: "164", MotherTongueName: "Bihari" },
    { MothertoungeCode: "165", MotherTongueName: "Bodo" },
    { MothertoungeCode: "248", MotherTongueName: "Burmese" },
    { MothertoungeCode: "166", MotherTongueName: "Chinese" },
    { MothertoungeCode: "167", MotherTongueName: "Coorgi" },
    { MothertoungeCode: "168", MotherTongueName: "Danish" },
    { MothertoungeCode: "169", MotherTongueName: "Dogri" },
    { MothertoungeCode: "170", MotherTongueName: "Dutch" },
    { MothertoungeCode: "125", MotherTongueName: "English" },
    { MothertoungeCode: "171", MotherTongueName: "Farsi" },
    { MothertoungeCode: "172", MotherTongueName: "French" },
    { MothertoungeCode: "254", MotherTongueName: "Garhwali" },
    { MothertoungeCode: "173", MotherTongueName: "Garo" },
    { MothertoungeCode: "174", MotherTongueName: "German" },
    { MothertoungeCode: "175", MotherTongueName: "Greek" },
    { MothertoungeCode: "176", MotherTongueName: "Gujarati" },
    { MothertoungeCode: "177", MotherTongueName: "Himachali" },
    { MothertoungeCode: "52", MotherTongueName: "Hindi" },
    { MothertoungeCode: "178", MotherTongueName: "Hmar" },
    { MothertoungeCode: "179", MotherTongueName: "Jaintia" },
    { MothertoungeCode: "247", MotherTongueName: "Japanese" },
    { MothertoungeCode: "181", MotherTongueName: "Kaasi" },
    { MothertoungeCode: "182", MotherTongueName: "Kabui" },
    { MothertoungeCode: "183", MotherTongueName: "Kachchi" },
    { MothertoungeCode: "184", MotherTongueName: "Kannada" },
    { MothertoungeCode: "185", MotherTongueName: "Karbi" },
    { MothertoungeCode: "186", MotherTongueName: "Karfi" },
    { MothertoungeCode: "187", MotherTongueName: "Kashmiri" },
    { MothertoungeCode: "188", MotherTongueName: "Khasi" },
    { MothertoungeCode: "190", MotherTongueName: "Kodava takk" },
    { MothertoungeCode: "189", MotherTongueName: "Kodawa" },
    { MothertoungeCode: "191", MotherTongueName: "Konkani" },
    { MothertoungeCode: "192", MotherTongueName: "Korean" },
    { MothertoungeCode: "193", MotherTongueName: "Kuki" },
    { MothertoungeCode: "194", MotherTongueName: "Kumaoni" },
    { MothertoungeCode: "255", MotherTongueName: "Kumauni" },
    { MothertoungeCode: "195", MotherTongueName: "Kutchi" },
    { MothertoungeCode: "196", MotherTongueName: "Lambani" },
    { MothertoungeCode: "197", MotherTongueName: "Latin" },
    { MothertoungeCode: "199", MotherTongueName: "Maithali" },
    { MothertoungeCode: "262", MotherTongueName: "Maithili" },
    { MothertoungeCode: "241", MotherTongueName: "Malay" },
    { MothertoungeCode: "200", MotherTongueName: "Malayalam" },
    { MothertoungeCode: "201", MotherTongueName: "Malayasian" },
    { MothertoungeCode: "202", MotherTongueName: "Mandarin" },
    { MothertoungeCode: "203", MotherTongueName: "Manipuri" },
    { MothertoungeCode: "204", MotherTongueName: "Marathi" },
    { MothertoungeCode: "257", MotherTongueName: "Marwadi" },
    { MothertoungeCode: "198", MotherTongueName: "Marwari" },
    { MothertoungeCode: "206", MotherTongueName: "Mizo" },
    { MothertoungeCode: "207", MotherTongueName: "Mukhia" },
    { MothertoungeCode: "208", MotherTongueName: "Nagamese" },
    { MothertoungeCode: "209", MotherTongueName: "Nawaythi" },
    { MothertoungeCode: "210", MotherTongueName: "Nepali" },
    { MothertoungeCode: "211", MotherTongueName: "Oriya" },
    { MothertoungeCode: "212", MotherTongueName: "Pahadi" },
    { MothertoungeCode: "213", MotherTongueName: "Paite" },
    { MothertoungeCode: "214", MotherTongueName: "Parsi" },
    { MothertoungeCode: "215", MotherTongueName: "Persian" },
    { MothertoungeCode: "216", MotherTongueName: "Punjabi" },
    { MothertoungeCode: "217", MotherTongueName: "Pzongkma" },
    { MothertoungeCode: "218", MotherTongueName: "Rajasthani" },
    { MothertoungeCode: "261", MotherTongueName: "RRR Lang" },
    { MothertoungeCode: "219", MotherTongueName: "Russian" },
    { MothertoungeCode: "220", MotherTongueName: "Sanskrit" },
    { MothertoungeCode: "263", MotherTongueName: "Santali" },
    { MothertoungeCode: "221", MotherTongueName: "Sema" },
    { MothertoungeCode: "222", MotherTongueName: "Setswana" },
    { MothertoungeCode: "223", MotherTongueName: "Sikkimese" },
    { MothertoungeCode: "224", MotherTongueName: "Sindhi" },
    { MothertoungeCode: "225", MotherTongueName: "Sinhalese" },
    { MothertoungeCode: "226", MotherTongueName: "Soheli" },
    { MothertoungeCode: "227", MotherTongueName: "Sourashtra" },
    { MothertoungeCode: "228", MotherTongueName: "Spanish" },
    { MothertoungeCode: "229", MotherTongueName: "Sumi Naga" },
    { MothertoungeCode: "230", MotherTongueName: "Swahilli" },
    { MothertoungeCode: "231", MotherTongueName: "Tamil" },
    { MothertoungeCode: "232", MotherTongueName: "Tangkhul" },
    { MothertoungeCode: "233", MotherTongueName: "Telugu" },
    { MothertoungeCode: "234", MotherTongueName: "Thaadou" },
    { MothertoungeCode: "235", MotherTongueName: "Thai" },
    { MothertoungeCode: "236", MotherTongueName: "Tibetian" },
    { MothertoungeCode: "237", MotherTongueName: "Tulu" },
    { MothertoungeCode: "238", MotherTongueName: "Urdu" },
    { MothertoungeCode: "239", MotherTongueName: "Zeliang" },
    { MothertoungeCode: "158", MotherTongueName: "Others" },
  ],
  ReligionData: [
    { ReligionCode: "", ReligionName: "" },
    { ReligionCode: "1", ReligionName: "Buddhist" },
    { ReligionCode: "2", ReligionName: "Christian" },
    { ReligionCode: "11", ReligionName: "HINDHU" },
    { ReligionCode: "3", ReligionName: "Hindu" },
    { ReligionCode: "4", ReligionName: "Jain" },
    { ReligionCode: "10", ReligionName: "Judaism" },
    { ReligionCode: "5", ReligionName: "Muslim" },
    { ReligionCode: "7", ReligionName: "Sikh" },
    { ReligionCode: "8", ReligionName: "Zorastrian" },
    { ReligionCode: "6", ReligionName: "Others" },
  ],
  CasteData: [
    { CasteCode: "1", CasteName: "BC" },
    { CasteCode: "24", CasteName: "Brahmin" },
    { CasteCode: "27", CasteName: "Budha" },
    { CasteCode: "32", CasteName: "Budhist" },
    { CasteCode: "13", CasteName: "Bunts" },
    { CasteCode: "33", CasteName: "catholic" },
    { CasteCode: "23", CasteName: "CKP" },
    { CasteCode: "22", CasteName: "Deshastha Brahmin" },
    { CasteCode: "34", CasteName: "Devanga" },
    { CasteCode: "35", CasteName: "General" },
    { CasteCode: "36", CasteName: "Genral" },
    { CasteCode: "37", CasteName: "Goud Brahmin" },
    { CasteCode: "11", CasteName: "Gowda Saraswat Brahmin" },
    { CasteCode: "38", CasteName: "Hindu" },
    { CasteCode: "30", CasteName: "Hindu Jain" },
    { CasteCode: "39", CasteName: "Hindu-Maratha" },
    { CasteCode: "40", CasteName: "Jain" },
    { CasteCode: "20", CasteName: "Karhade Brahmin" },
    { CasteCode: "19", CasteName: "kayastha" },
    { CasteCode: "21", CasteName: "Kokanastha Brahmin" },
    { CasteCode: "12", CasteName: "Liggayatha" },
    { CasteCode: "28", CasteName: "Maratha" },
    { CasteCode: "2", CasteName: "MBC" },
    { CasteCode: "26", CasteName: "Mogaveera" },
    { CasteCode: "29", CasteName: "Nair" },
    { CasteCode: "25", CasteName: "NT" },
    { CasteCode: "5", CasteName: "OBC" },
    { CasteCode: "41", CasteName: "OC" },
    { CasteCode: "42", CasteName: "Open" },
    { CasteCode: "43", CasteName: "Paomashali" },
    { CasteCode: "15", CasteName: "Pathan" },
    { CasteCode: "18", CasteName: "PRAJAPATI" },
    { CasteCode: "44", CasteName: "Punjabi" },
    { CasteCode: "45", CasteName: "Rajput" },
    { CasteCode: "16", CasteName: "Reddy" },
    { CasteCode: "3", CasteName: "SC" },
    { CasteCode: "46", CasteName: "SCBC" },
    { CasteCode: "4", CasteName: "ST" },
    { CasteCode: "31", CasteName: "Sunni" },
    { CasteCode: "17", CasteName: "Telaga Naidu" },
    { CasteCode: "47", CasteName: "Teli" },
    { CasteCode: "6", CasteName: "Others" },
  ],
  QualificationOptions: [
    { qualificationCode: "113", qualificationName: "10th Standard" },
    { qualificationCode: "78", qualificationName: "12th Standard" },
    {
      category: "Diploma",
      options: [
        { qualificationCode: "451", qualificationName: "Qualification" },
        { qualificationCode: "455", qualificationName: "B.B.I." },
        { qualificationCode: "471", qualificationName: "Diploma" },
        { qualificationCode: "472", qualificationName: "Diploma in Info Tech" },
        {
          qualificationCode: "473",
          qualificationName: "Diploma in Mechanical Engineering",
        },
        {
          qualificationCode: "528",
          qualificationName: "Graduate Diploma in Business Administration",
        },
        { qualificationCode: "535", qualificationName: "Others" },
      ],
    },
    {
      category: "Graduation",
      options: [
        { qualificationCode: "42", qualificationName: "B.A" },
        { qualificationCode: "49", qualificationName: "B.Com" },
        { qualificationCode: "52", qualificationName: "B.E" },
        { qualificationCode: "156", qualificationName: "B.Pharm" },
        { qualificationCode: "160", qualificationName: "B.Sc" },
        { qualificationCode: "188", qualificationName: "B.L / L.L.B" },
        { qualificationCode: "263", qualificationName: "B.Tech" },
        { qualificationCode: "299", qualificationName: "Graduate" },
        { qualificationCode: "302", qualificationName: "B.B.M" },
        { qualificationCode: "307", qualificationName: "B.B.A" },
        { qualificationCode: "309", qualificationName: "B.M.S" },
        { qualificationCode: "437", qualificationName: "BCA" },
        { qualificationCode: "439", qualificationName: "B.Ed." },
        { qualificationCode: "454", qualificationName: "B.A (Hons.)" },
        { qualificationCode: "456", qualificationName: "B.Com (Hons.)" },
        { qualificationCode: "457", qualificationName: "B.Sc (Hons.)" },
        { qualificationCode: "458", qualificationName: "BBS" },
        { qualificationCode: "459", qualificationName: "BHM" },
        { qualificationCode: "460", qualificationName: "BMM" },
        { qualificationCode: "461", qualificationName: "BMS" },
        { qualificationCode: "462", qualificationName: "CCFA" },
        { qualificationCode: "508", qualificationName: "B. Sc. (IT)" },
        {
          qualificationCode: "509",
          qualificationName: "Bachelor of Business Studies (BBS)",
        },
        { qualificationCode: "511", qualificationName: "B.B.I." },
        { qualificationCode: "513", qualificationName: "BRS" },
        {
          qualificationCode: "514",
          qualificationName: "Entreprenership and Economics (Business)",
        },
        { qualificationCode: "520", qualificationName: "Others" },
        { qualificationCode: "522", qualificationName: "F.Y.B.COM" },
        { qualificationCode: "529", qualificationName: "S.Y.B.COM" },
        { qualificationCode: "548", qualificationName: "TestGraduation" },
        { qualificationCode: "549", qualificationName: "testGraduation2" },
        { qualificationCode: "550", qualificationName: "test3" },
      ],
    },
    {
      category: "Post Graduation",
      options: [
        { qualificationCode: "61", qualificationName: "M.A" },
        { qualificationCode: "64", qualificationName: "M.Com" },
        { qualificationCode: "66", qualificationName: "M.E" },
        { qualificationCode: "87", qualificationName: "M.Pharm" },
        { qualificationCode: "88", qualificationName: "M.Sc" },
        { qualificationCode: "108", qualificationName: "M.B.A" },
        { qualificationCode: "149", qualificationName: "M.B.B.S" },
        { qualificationCode: "161", qualificationName: "M.C.A" },
        { qualificationCode: "162", qualificationName: "M.D / M.S" },
        { qualificationCode: "165", qualificationName: "M.L / L.L.M" },
        { qualificationCode: "275", qualificationName: "M.Tech" },
        { qualificationCode: "303", qualificationName: "MPM" },
        { qualificationCode: "305", qualificationName: "M.M.M" },
        { qualificationCode: "310", qualificationName: "M.M.S" },
        { qualificationCode: "421", qualificationName: "MSW" },
        { qualificationCode: "428", qualificationName: "M Phill" },
        { qualificationCode: "482", qualificationName: "M. Phil." },
        { qualificationCode: "483", qualificationName: "M.A (Hons.)" },
        { qualificationCode: "484", qualificationName: "M.F.M" },
        { qualificationCode: "485", qualificationName: "M.H.R.D.M" },
        { qualificationCode: "486", qualificationName: "M.I.M" },
        { qualificationCode: "487", qualificationName: "M.I.T." },
        {
          qualificationCode: "488",
          qualificationName: "Master in Rural Managment",
        },
        {
          qualificationCode: "489",
          qualificationName: "Master of Business Finance (MBF)",
        },
        { qualificationCode: "490", qualificationName: "MS" },
        { qualificationCode: "510", qualificationName: "PGDMM - Marketing" },
        { qualificationCode: "516", qualificationName: "Company Secretaries" },
        { qualificationCode: "517", qualificationName: "FY B.Sc." },
        { qualificationCode: "518", qualificationName: "PH.D" },
        { qualificationCode: "521", qualificationName: "Executive MBA" },
        {
          qualificationCode: "523",
          qualificationName: "Company Secretary (CS)",
        },
        { qualificationCode: "524", qualificationName: "ICWA" },
        { qualificationCode: "526", qualificationName: "PGDFM" },
        { qualificationCode: "530", qualificationName: "Post Graduation" },
        { qualificationCode: "531", qualificationName: "Others" },
        { qualificationCode: "532", qualificationName: "HDSM" },
        {
          qualificationCode: "533",
          qualificationName: "Chartered Financial Analyst (CFA)",
        },
        { qualificationCode: "534", qualificationName: "PGDMM" },
      ],
    },
    {
      category: "Post Graduation Diploma",
      options: [
        { qualificationCode: "285", qualificationName: "PGDM" },
        { qualificationCode: "290", qualificationName: "PGDCA" },
        { qualificationCode: "464", qualificationName: "PGDMM" },
        { qualificationCode: "491", qualificationName: "PGDBA" },
        { qualificationCode: "492", qualificationName: "PGDBM" },
        { qualificationCode: "493", qualificationName: "PGDCM" },
        { qualificationCode: "494", qualificationName: "PGDFM" },
        { qualificationCode: "495", qualificationName: "PGDIM" },
        { qualificationCode: "496", qualificationName: "PGDIR&amp;PM" },
        { qualificationCode: "497", qualificationName: "PGDMS" },
        { qualificationCode: "498", qualificationName: "PGDPM" },
        { qualificationCode: "500", qualificationName: "Post Graduation" },
        { qualificationCode: "527", qualificationName: "Others" },
        { qualificationCode: "551", qualificationName: "10th" },
      ],
    },
    {
      category: "Ph.D",
      options: [
        { qualificationCode: "447", qualificationName: "Physics" },
        { qualificationCode: "448", qualificationName: "Chemistry" },
        { qualificationCode: "449", qualificationName: "Computer Science" },
      ],
    },
    {
      category: "CA",
      options: [
        { qualificationCode: "400", qualificationName: "CA Foundation" },
        { qualificationCode: "404", qualificationName: "CA Inter" },
        { qualificationCode: "405", qualificationName: "CA Final Exam" },
      ],
    },
  ],
};

export default ArrayDummyData;
