import { FaChartLine, FaUsers, FaBriefcase, FaClipboardCheck, FaCog, FaRegHandshake, FaNewspaper, FaYelp, FaBalanceScale, FaUser, FaUserPlus, FaHourglassStart, FaPaperPlane, FaHourglassHalf, FaCar, FaSitemap, FaArrowRight, FaClock, FaMapMarkerAlt, FaDatabase, FaUserTie, FaCogs } from 'react-icons/fa';
import { IoMdTime } from 'react-icons/io';
import { MdBusiness } from 'react-icons/md';
import { GiTransportationRings } from 'react-icons/gi';


export const Sec_Modules = [
    { Module_Code: 3, Module_Name: "Performance & Goals", Typeofuser: "H", Display: 1, Display_Order: 6, Img_Src: FaChartLine ,path:"/"},
    { Module_Code: 999, Module_Name: "Workline Setup", Typeofuser: "H", Display: 1, Display_Order: 13, Img_Src: MdBusiness ,path:"/"},
    { Module_Code: 15, Module_Name: "Workforce Management", Typeofuser: "H", Display: 1, Display_Order: 1, Img_Src: FaUsers ,path:"wfm?ModeCode="},
    { Module_Code: 338, Module_Name: "RECRUITMENT", Typeofuser: "S", Display: 1, Display_Order: 2, Img_Src: FaClipboardCheck ,path:"/"},
    { Module_Code: 436, Module_Name: "Business Process", Typeofuser: "H", Display: 1, Display_Order: 509, Img_Src: FaCog ,path:"/"},
    { Module_Code: 14, Module_Name: "Talent Acquisition", Typeofuser: "H", Display: 1, Display_Order: 2, Img_Src: FaRegHandshake ,path:"/"},
    { Module_Code: 20, Module_Name: "Enterprise Config Studio", Typeofuser: "H", Display: 1, Display_Order: 1, Img_Src: MdBusiness ,path:"/"},
    { Module_Code: 332, Module_Name: "RECRUITMENT", Typeofuser: 5, Display: 1, Display_Order: 2, Img_Src: FaClipboardCheck ,path:"/"},
    { Module_Code: 148, Module_Name: "RECRUITMENT", Typeofuser: 4, Display: 1, Display_Order: 2, Img_Src: FaClipboardCheck ,path:"/"},
    { Module_Code: 60, Module_Name: "Learning & Development", Typeofuser: "E", Display: 1, Display_Order: 7, Img_Src: GiTransportationRings ,path:"/"},
    { Module_Code: 61, Module_Name: "Workforce Management", Typeofuser: "E", Display: 1, Display_Order: 1, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 63, Module_Name: "Performance & Goals", Typeofuser: "E", Display: 1, Display_Order: 6, Img_Src: FaChartLine ,path:"/"},
    { Module_Code: 99, Module_Name: "Talent Acquisition", Typeofuser: "E", Display: 1, Display_Order: 2, Img_Src: FaRegHandshake ,path:"/"},
    { Module_Code: 186, Module_Name: "Performance Management", Typeofuser: "A", Display: 1, Display_Order: 2, Img_Src: FaChartLine ,path:"/"},
    { Module_Code: 306, Module_Name: "Attendance & Timeoff", Typeofuser: "E", Display: 1, Display_Order: 3, Img_Src: IoMdTime ,path:"/"},
    { Module_Code: 209, Module_Name: "Performance Management", Typeofuser: "R", Display: 1, Display_Order: 3, Img_Src: FaChartLine ,path:"/"},
    { Module_Code: 212, Module_Name: "HR HELP DESK", Typeofuser: 8, Display: 1, Display_Order: 1, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 337, Module_Name: "RECRUITMENT", Typeofuser: "C", Display: 1, Display_Order: 2, Img_Src: FaClipboardCheck ,path:"/"},
    { Module_Code: 400, Module_Name: "Workforce Engagement", Typeofuser: "E", Display: 1, Display_Order: 10, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 342, Module_Name: "Recruitment", Typeofuser: "I", Display: 1, Display_Order: 2, Img_Src: FaClipboardCheck ,path:"/"},
    { Module_Code: 343, Module_Name: "RECRUITMENT", Typeofuser: "J", Display: 1, Display_Order: 2, Img_Src: FaClipboardCheck ,path:"/"},
    { Module_Code: 184, Module_Name: "Learning & Development", Typeofuser: "H", Display: 1, Display_Order: 7, Img_Src: GiTransportationRings ,path:"/"},
    { Module_Code: 216, Module_Name: "Workforce Analytics", Typeofuser: "H", Display: 1, Display_Order: 12, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 327, Module_Name: "Organisation Structure", Typeofuser: "Y", Display: 1, Display_Order: 1, Img_Src: MdBusiness ,path:"/"},
    { Module_Code: 305, Module_Name: "Attendance & Timeoff", Typeofuser: "H", Display: 1, Display_Order: 4, Img_Src: IoMdTime ,path:"/"},
    { Module_Code: 309, Module_Name: "Compensation & Benefits", Typeofuser: "E", Display: 1, Display_Order: 5, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 312, Module_Name: "Compensation & Benefits", Typeofuser: "H", Display: 1, Display_Order: 5, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 389, Module_Name: "e-Exit Management", Typeofuser: "A", Display: 1, Display_Order: 13, Img_Src: FaClipboardCheck ,path:"/"},
    { Module_Code: 355, Module_Name: "Travel Management", Typeofuser: "H", Display: 1, Display_Order: 8, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 356, Module_Name: "Travel Management", Typeofuser: "A", Display: 1, Display_Order: 15, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 357, Module_Name: "Travel Management", Typeofuser: "A", Display: 1, Display_Order: 9, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 358, Module_Name: "Travel Management", Typeofuser: "T", Display: 1, Display_Order: 15, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 359, Module_Name: "Travel Management", Typeofuser: "V", Display: 1, Display_Order: 1, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 360, Module_Name: "Expenses Management", Typeofuser: "E", Display: 1, Display_Order: 9, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 361, Module_Name: "Expenses Mgmnt", Typeofuser: "A", Display: 1, Display_Order: 10, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 362, Module_Name: "Expenses Management", Typeofuser: "H", Display: 1, Display_Order: 9, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 363, Module_Name: "Travel Management", Typeofuser: "E", Display: 1, Display_Order: 8, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 367, Module_Name: "Travel Management", Typeofuser: "Z", Display: 1, Display_Order: 5, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 432, Module_Name: "360° FEEDBACK", Typeofuser: "R", Display: 1, Display_Order: 4, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 406, Module_Name: "Employee Development", Typeofuser: "N", Display: 1, Display_Order: 1, Img_Src: GiTransportationRings ,path:"/"},
    { Module_Code: 399, Module_Name: "Workforce Engagement", Typeofuser: "H", Display: 1, Display_Order: 15, Img_Src: FaUsers ,path:"/"},
    { Module_Code: 437, Module_Name: "Business Process", Typeofuser: "E", Display: 1, Display_Order: 11, Img_Src: FaCog ,path:"/"},
  ];
  

 
export const Sec_Menu_Group = [
    { Group_Code: 84, Module_Code: 305, Group_Name: 'Rostering', Display_Order: 1, Group_Icon: FaNewspaper},
    { Group_Code: 14, Module_Code: 3, Group_Name: 'Performance Diary', Display_Order: 10, Group_Icon: FaYelp},
    { Group_Code: 17, Module_Code: 14, Group_Name: 'Budgeting & Planning', Display_Order: 5, Group_Icon: FaBalanceScale},
    { Group_Code: 28, Module_Code: 14, Group_Name: 'Utilities', Display_Order: 23, Group_Icon: ''},
    { Group_Code: 707, Module_Code: 306, Group_Name: 'About Me', Display_Order: 1, Group_Icon: FaUser},
    { Group_Code: 723, Module_Code: 15, Group_Name: 'About Me', Display_Order: 1, Group_Icon: FaUser},
    { Group_Code: 724, Module_Code: 15, Group_Name: 'About My Team', Display_Order: 2, Group_Icon: FaUserPlus},
    { Group_Code: 776, Module_Code: 15, Group_Name: 'About My Sphere', Display_Order: 3, Group_Icon: FaUsers},
    { Group_Code: 29, Module_Code: 15, Group_Name: 'Employee Profile Reports', Display_Order: 4, Group_Icon: ''},
    { Group_Code: 708, Module_Code: 306, Group_Name: 'About My Team', Display_Order: 2, Group_Icon: FaUserPlus},
    { Group_Code: 85, Module_Code: 305, Group_Name: 'Attendance', Display_Order: 2, Group_Icon: FaUserPlus},
    { Group_Code: 709, Module_Code: 306, Group_Name: 'About My Sphere', Display_Order: 3, Group_Icon: FaUsers},
    { Group_Code: 154, Module_Code: 312, Group_Name: 'Comp Structuring & Pre Process Preparation', Display_Order: 30, Group_Icon: FaHourglassStart},
    { Group_Code: 99, Module_Code: 312, Group_Name: 'Performance Compensation Review', Display_Order: 20, Group_Icon: FaPaperPlane},
    { Group_Code: 155, Module_Code: 312, Group_Name: 'Salary & Tax Processing', Display_Order: 40, Group_Icon: FaHourglassHalf},
    { Group_Code: 701, Module_Code: 61, Group_Name: 'About Me', Display_Order: 1, Group_Icon: FaUser},
    { Group_Code: 702, Module_Code: 61, Group_Name: 'About My Team', Display_Order: 2, Group_Icon: FaUserPlus},
    { Group_Code: 509, Module_Code: 355, Group_Name: 'Travel Process', Display_Order: 3, Group_Icon: FaCar},
    { Group_Code: 510, Module_Code: 436, Group_Name: 'Payment Management', Display_Order: 160, Group_Icon: ''},
    { Group_Code: 511, Module_Code: 436, Group_Name: 'SPOC Communication', Display_Order: 10, Group_Icon: ''},
    { Group_Code: 703, Module_Code: 61, Group_Name: 'About My Sphere', Display_Order: 3, Group_Icon: FaUsers},
    { Group_Code: 156, Module_Code: 212, Group_Name: 'HR Service Desk', Display_Order: 1, Group_Icon: ''},
    { Group_Code: 710, Module_Code: 309, Group_Name: 'About Me', Display_Order: 1, Group_Icon: FaUser},
    { Group_Code: 711, Module_Code: 309, Group_Name: 'About My Team', Display_Order: 2, Group_Icon: ''},
    { Group_Code: 814, Module_Code: 312, Group_Name: 'DSOP', Display_Order: 0, Group_Icon: ''},
    { Group_Code: 712, Module_Code: 309, Group_Name: 'About My Sphere', Display_Order: 3, Group_Icon: ''},
    { Group_Code: 713, Module_Code: 360, Group_Name: 'About Me', Display_Order: 1, Group_Icon: FaUser},
    { Group_Code: 714, Module_Code: 360, Group_Name: 'About My Team', Display_Order: 2, Group_Icon: FaUserPlus},
    { Group_Code: 715, Module_Code: 363, Group_Name: 'About Me', Display_Order: 1, Group_Icon: FaUser},
    { Group_Code: 716, Module_Code: 363, Group_Name: 'About My Team', Display_Order: 2, Group_Icon: FaUserPlus},
    { Group_Code: 717, Module_Code: 63, Group_Name: 'About Me', Display_Order: 1, Group_Icon: FaUser},
    { Group_Code: 718, Module_Code: 63, Group_Name: 'About My Team', Display_Order: 2, Group_Icon: FaUserPlus},
    { Group_Code: 719, Module_Code: 63, Group_Name: 'About My Sphere', Display_Order: 3, Group_Icon: FaUsers},
    { Group_Code: 720, Module_Code: 99, Group_Name: 'About Me', Display_Order: 1, Group_Icon: FaUser},
    { Group_Code: 721, Module_Code: 99, Group_Name: 'About My Team', Display_Order: 2, Group_Icon: FaUsers},
    { Group_Code: 151, Module_Code: 14, Group_Name: 'Manpower Requisition Form', Display_Order: 3, Group_Icon: ''},
    { Group_Code: 163, Module_Code: 305, Group_Name: 'Custom Policy', Display_Order: 1, Group_Icon: FaCog},
    { Group_Code: 722, Module_Code: 99, Group_Name: 'About My Sphere', Display_Order: 3, Group_Icon: FaUserPlus},
    { Group_Code: 157, Module_Code: 305, Group_Name: 'Payroll Handoff', Display_Order: 6, Group_Icon: FaUserPlus},
    { Group_Code: 750, Module_Code: 60, Group_Name: 'About Me', Display_Order: 1, Group_Icon: FaUser},
    { Group_Code: 751, Module_Code: 60, Group_Name: 'About My Team', Display_Order: 2, Group_Icon: FaUserPlus},
    { Group_Code: 158, Module_Code: 999, Group_Name: 'Config Studio', Display_Order: 1, Group_Icon: FaSitemap},
    { Group_Code: 159, Module_Code: 999, Group_Name: 'Workflow Config', Display_Order: 2, Group_Icon: FaArrowRight},
    { Group_Code: 723, Module_Code: 400, Group_Name: 'About Me', Display_Order: 1, Group_Icon: FaUser},
    { Group_Code: 724, Module_Code: 400, Group_Name: 'About My Team', Display_Order: 2, Group_Icon: FaUserPlus},
    { Group_Code: 752, Module_Code: 20, Group_Name: 'Workflow Management', Display_Order: 1, Group_Icon: GiTransportationRings},
    { Group_Code: 753, Module_Code: 20, Group_Name: 'Release Management', Display_Order: 2, Group_Icon: FaSitemap},
    { Group_Code: 160, Module_Code: 15, Group_Name: 'Asset Management', Display_Order: 5, Group_Icon: FaUserTie},
    { Group_Code: 754, Module_Code: 999, Group_Name: 'Form Config', Display_Order: 3, Group_Icon: FaUser},
    { Group_Code: 755, Module_Code: 399, Group_Name: 'Timesheet', Display_Order: 150, Group_Icon: FaClock},
    { Group_Code: 756, Module_Code: 362, Group_Name: 'Vendor Management', Display_Order: 8, Group_Icon: FaUsers},
    { Group_Code: 757, Module_Code: 360, Group_Name: 'About My Sphere', Display_Order: 3, Group_Icon: FaUsers},
    { Group_Code: 775, Module_Code: 363, Group_Name: 'About My Sphere', Display_Order: 3, Group_Icon: FaUser},
    { Group_Code: 776, Module_Code: 363, Group_Name: 'About My Sphere', Display_Order: 3, Group_Icon: FaUsers},
    { Group_Code: 161, Module_Code: 20, Group_Name: 'Organisation Structure', Display_Order: 12, Group_Icon: FaMapMarkerAlt},
    { Group_Code: 777, Module_Code: 15, Group_Name: 'PIP', Display_Order: 6, Group_Icon: ''},
    { Group_Code: 778, Module_Code: 400, Group_Name: 'About My Sphere', Display_Order: 3, Group_Icon: FaUsers},
    { Group_Code: 162, Module_Code: 399, Group_Name: 'Dashboard', Display_Order: 160, Group_Icon: FaUsers},
    { Group_Code: 779, Module_Code: 399, Group_Name: 'Circular', Display_Order: 161, Group_Icon: ''},
    { Group_Code: 780, Module_Code: 3, Group_Name: 'MI Process', Display_Order: 20, Group_Icon: FaBriefcase},
    { Group_Code: 781, Module_Code: 436, Group_Name: 'Legal Notice', Display_Order: 20, Group_Icon: ''},
    { Group_Code: 782, Module_Code: 436, Group_Name: 'Access Management', Display_Order: 10, Group_Icon: ''},
    { Group_Code: 783, Module_Code: 436, Group_Name: 'About Me', Display_Order: 1, Group_Icon: FaUser},
    { Group_Code: 786, Module_Code: 436, Group_Name: 'Account Opening', Display_Order: 30, Group_Icon: ''},
    { Group_Code: 787, Module_Code: 436, Group_Name: 'Branch Audit', Display_Order: 40, Group_Icon: ''},
    { Group_Code: 788, Module_Code: 999, Group_Name: 'DB Version Control', Display_Order: 4, Group_Icon: FaDatabase},
    { Group_Code: 789, Module_Code: 399, Group_Name: 'BOT', Display_Order: 100, Group_Icon: ''},
    { Group_Code: 790, Module_Code: 305, Group_Name: 'TMS', Display_Order: 80, Group_Icon: FaUserTie},
    { Group_Code: 791, Module_Code: 305, Group_Name: 'DB Management', Display_Order: 20, Group_Icon: ''},
    { Group_Code: 792, Module_Code: 305, Group_Name: 'Config Studio', Display_Order: 1, Group_Icon: FaCog},
    { Group_Code: 793, Module_Code: 20, Group_Name: 'Report Management', Display_Order: 3, Group_Icon: FaCogs },
    { Group_Code: 794, Module_Code: 20, Group_Name: 'Overview', Display_Order: 20, Group_Icon: FaCogs},
    { Group_Code: 795, Module_Code: 20, Group_Name: 'Workflow Config', Display_Order: 5, Group_Icon: FaCogs},
    { Group_Code: 796, Module_Code: 20, Group_Name: 'Budget Planning', Display_Order: 30, Group_Icon: FaUserTie},
    { Group_Code: 797, Module_Code: 20, Group_Name: 'Contract Management', Display_Order: 40, Group_Icon: FaUserTie},
    { Group_Code: 798, Module_Code: 20, Group_Name: 'Employee Profile', Display_Order: 1, Group_Icon: FaUserTie},
    { Group_Code: 799, Module_Code: 20, Group_Name: 'Asset Management', Display_Order: 160, Group_Icon: FaUserTie},
    { Group_Code: 800, Module_Code: 20, Group_Name: 'Skill Development', Display_Order: 160, Group_Icon: FaUserTie  },
  ];
  

export const Sec_Menu_SubGroup = [
    { SubGroupCode: 1, SubGroupName: "Activation Configuration", DisplayOrder: 1, GroupCode: 1},
    { SubGroupCode: 2, SubGroupName: "Reset Configuration", DisplayOrder: 4, GroupCode: 1 },
    { SubGroupCode: 3, SubGroupName: "Appraisal Analytics Studio", DisplayOrder: 20, GroupCode: 1 },
    { SubGroupCode: 4, SubGroupName: "Project Review", DisplayOrder: 6, GroupCode: 1 },
    { SubGroupCode: 5, SubGroupName: "Review Process", DisplayOrder: 2, GroupCode: 2 },
    { SubGroupCode: 6, SubGroupName: "Reports", DisplayOrder: 3, GroupCode: 2 },
    { SubGroupCode: 7, SubGroupName: "Configuration Studio", DisplayOrder: 2, GroupCode: 8 },
    { SubGroupCode: 8, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 4 },
    { SubGroupCode: 9, SubGroupName: "KRA Process Studio", DisplayOrder: 3, GroupCode: 4 },
    { SubGroupCode: 10, SubGroupName: "Analytics Studio", DisplayOrder: 10, GroupCode: 4 },
    { SubGroupCode: 11, SubGroupName: "Custom Abstracts", DisplayOrder: 21, GroupCode: 5 },
    { SubGroupCode: 12, SubGroupName: "Configuration Studio", DisplayOrder: 2, GroupCode: 5 },
    { SubGroupCode: 13, SubGroupName: "Review Configuration", DisplayOrder: 4, GroupCode: 5 },
    { SubGroupCode: 14, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 6 },
    { SubGroupCode: 15, SubGroupName: "Review Mapping", DisplayOrder: 5, GroupCode: 5 },
    { SubGroupCode: 16, SubGroupName: "Review Mapping Abstract", DisplayOrder: 16, GroupCode: 5 },
    { SubGroupCode: 17, SubGroupName: "Analytics Studio", DisplayOrder: 10, GroupCode: 8 },
    { SubGroupCode: 18, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 9 },
    { SubGroupCode: 19, SubGroupName: "Activation", DisplayOrder: 4, GroupCode: 8 },
    { SubGroupCode: 20, SubGroupName: "Imports", DisplayOrder: 4, GroupCode: 30 },
    { SubGroupCode: 24, SubGroupName: "Configuration Studio", DisplayOrder: 2, GroupCode: 14 },
    { SubGroupCode: 25, SubGroupName: "Dairy Process", DisplayOrder: 4, GroupCode: 14 },
    { SubGroupCode: 26, SubGroupName: "Analytics Studio", DisplayOrder: 12, GroupCode: 14 },
    { SubGroupCode: 27, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 15 },
    { SubGroupCode: 28, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 16 },
    { SubGroupCode: 29, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 17 },
    { SubGroupCode: 30, SubGroupName: "Analytics Studio", DisplayOrder: 5, GroupCode: 17 },
    { SubGroupCode: 31, SubGroupName: "Budget Process Studio", DisplayOrder: 2, GroupCode: 17 },
    { SubGroupCode: 32, SubGroupName: "Requisition Process Studio", DisplayOrder: 3, GroupCode: 17 },
    { SubGroupCode: 33, SubGroupName: "Imports", DisplayOrder: 4, GroupCode: 17 },
    { SubGroupCode: 34, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 18 },
    { SubGroupCode: 35, SubGroupName: "Reports", DisplayOrder: 3, GroupCode: 19 },
    { SubGroupCode: 36, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 20 },
    { SubGroupCode: 37, SubGroupName: "Analytics Studio", DisplayOrder: 4, GroupCode: 20 },
    { SubGroupCode: 38, SubGroupName: "Sourcing Process", DisplayOrder: 2, GroupCode: 20 },
    { SubGroupCode: 39, SubGroupName: "Candidate Entry", DisplayOrder: 3, GroupCode: 20 },
    { SubGroupCode: 40, SubGroupName: "Interview Process", DisplayOrder: 2, GroupCode: 21 },
    { SubGroupCode: 41, SubGroupName: "Utilities", DisplayOrder: 3, GroupCode: 21 },
    { SubGroupCode: 42, SubGroupName: "Analytics Studio", DisplayOrder: 5, GroupCode: 21 },
    { SubGroupCode: 43, SubGroupName: "Imports", DisplayOrder: 4, GroupCode: 21 },
    { SubGroupCode: 44, SubGroupName: "Screening Process", DisplayOrder: 1, GroupCode: 21 },
    { SubGroupCode: 45, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 22 },
    { SubGroupCode: 46, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 23 },
    { SubGroupCode: 47, SubGroupName: "Prejoining Process Studio", DisplayOrder: 1, GroupCode: 23 },
    { SubGroupCode: 48, SubGroupName: "Analytics Studio", DisplayOrder: 3, GroupCode: 23 },
    { SubGroupCode: 49, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 24 },
    { SubGroupCode: 50, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 25 },
    { SubGroupCode: 51, SubGroupName: "MRF Closure", DisplayOrder: 3, GroupCode: 26 },
    { SubGroupCode: 52, SubGroupName: "Appointment Process", DisplayOrder: 2, GroupCode: 26 },
    { SubGroupCode: 53, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 27 },
    { SubGroupCode: 54, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 28 },
    { SubGroupCode: 55, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 29 },
    { SubGroupCode: 56, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 30 },
    { SubGroupCode: 57, SubGroupName: "Onboarding Process Studio", DisplayOrder: 2, GroupCode: 30 },
    { SubGroupCode: 58, SubGroupName: "Analytics Studio", DisplayOrder: 4, GroupCode: 30 },
    { SubGroupCode: 59, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 31 },
    { SubGroupCode: 60, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 32 },
    { SubGroupCode: 61, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 33 },
    { SubGroupCode: 62, SubGroupName: "Reports", DisplayOrder: 3, GroupCode: 34 },
    { SubGroupCode: 63, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 35 },
    { SubGroupCode: 64, SubGroupName: "Job Status Process Studio", DisplayOrder: 2, GroupCode: 35 },
    { SubGroupCode: 65, SubGroupName: "Analytics Studio", DisplayOrder: 4, GroupCode: 35 },
    { SubGroupCode: 66, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 36 },
    { SubGroupCode: 67, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 37 },
    { SubGroupCode: 68, SubGroupName: "Peripheral Profile Process Studio", DisplayOrder: 3, GroupCode: 37 },
    { SubGroupCode: 69, SubGroupName: "Analytics Studio", DisplayOrder: 6, GroupCode: 37 },
    { SubGroupCode: 70, SubGroupName: "Imports", DisplayOrder: 5, GroupCode: 37 },
    { SubGroupCode: 71, SubGroupName: "Core Profile Process Studio", DisplayOrder: 2, GroupCode: 37 },
    { SubGroupCode: 72, SubGroupName: "Peripheral Profile Process Studio", DisplayOrder: 3, GroupCode: 37 },
    { SubGroupCode: 73, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 38 },
    { SubGroupCode: 74, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 39 },
    { SubGroupCode: 75, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 40 },
    { SubGroupCode: 76, SubGroupName: "Job Movement Process Studio", DisplayOrder: 2, GroupCode: 40 },
    { SubGroupCode: 77, SubGroupName: "Analytics Studio", DisplayOrder: 6, GroupCode: 40 },
    { SubGroupCode: 78, SubGroupName: "Imports", DisplayOrder: 5, GroupCode: 40 },
    { SubGroupCode: 79, SubGroupName: "Appraiser Modification Process Studio", DisplayOrder: 3, GroupCode: 40 },
    { SubGroupCode: 80, SubGroupName: "Movement Request Process Studio", DisplayOrder: 4, GroupCode: 40 },
    { SubGroupCode: 81, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 41 },
    { SubGroupCode: 82, SubGroupName: "Reports", DisplayOrder: 3, GroupCode: 42 },
    { SubGroupCode: 83, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 43 },
    { SubGroupCode: 84, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 44 },
    { SubGroupCode: 85, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 45 },
    { SubGroupCode: 86, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 46 },
    { SubGroupCode: 87, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 47 },
    { SubGroupCode: 88, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 48 },
    { SubGroupCode: 89, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 49 },
    { SubGroupCode: 90, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 50 },
    { SubGroupCode: 91, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 51 },
    { SubGroupCode: 92, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 52 },
    { SubGroupCode: 93, SubGroupName: "Separation Workflow Process Studio", DisplayOrder: 20, GroupCode: 52 },
    { SubGroupCode: 94, SubGroupName: "Analytics Studio", DisplayOrder: 70, GroupCode: 52 },
    { SubGroupCode: 95, SubGroupName: "Alumni Studio", DisplayOrder: 100, GroupCode: 52 },
    { SubGroupCode: 96, SubGroupName: "Update/Modify Separation Process Studio", DisplayOrder: 10, GroupCode: 52 },
    { SubGroupCode: 97, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 53 },
    { SubGroupCode: 98, SubGroupName: "Configuration Studio", DisplayOrder: 5, GroupCode: 54 },
    { SubGroupCode: 99, SubGroupName: "Process Studio", DisplayOrder: 6, GroupCode: 54 },
    { SubGroupCode: 100, SubGroupName: "Analytics Studio", DisplayOrder: 9, GroupCode: 54 },
    { SubGroupCode: 101, SubGroupName: "Imports", DisplayOrder: 8, GroupCode: 54 },
    { SubGroupCode: 102, SubGroupName: "Demographic Configuration Studio", DisplayOrder: 2, GroupCode: 54 },
    { SubGroupCode: 103, SubGroupName: "Organisational Configuration Studio", DisplayOrder: 1, GroupCode: 54 },
    { SubGroupCode: 104, SubGroupName: "Job Attributes Configuration Studio", DisplayOrder: 3, GroupCode: 54 },
    { SubGroupCode: 105, SubGroupName: "Workforce Settings Studio", DisplayOrder: 4, GroupCode: 54 },
    { SubGroupCode: 106, SubGroupName: "Process Setup Wizard", DisplayOrder: 7, GroupCode: 54 },
    { SubGroupCode: 107, SubGroupName: "Process Studio", DisplayOrder: 1, GroupCode: 55 },
    { SubGroupCode: 108, SubGroupName: "Analytics Studio", DisplayOrder: 5, GroupCode: 55 },
    { SubGroupCode: 109, SubGroupName: "Imports", DisplayOrder: 4, GroupCode: 55 },
    { SubGroupCode: 110, SubGroupName: "Request Enablement Config Studio", DisplayOrder: 2, GroupCode: 55 },
    { SubGroupCode: 111, SubGroupName: "Templates Config Studio", DisplayOrder: 3, GroupCode: 55 },
    { SubGroupCode: 112, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 56 },
    { SubGroupCode: 113, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 57 },
    { SubGroupCode: 114, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 58 },
    { SubGroupCode: 115, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 59 },
    { SubGroupCode: 116, SubGroupName: "Process Studio", DisplayOrder: 1, GroupCode: 60 },
    { SubGroupCode: 117, SubGroupName: "Analytics Studio", DisplayOrder: 5, GroupCode: 60 },
    { SubGroupCode: 118, SubGroupName: "Application Level Config Studio", DisplayOrder: 2, GroupCode: 60 },
    { SubGroupCode: 119, SubGroupName: "Access Control Config Studio", DisplayOrder: 3, GroupCode: 60 },
    { SubGroupCode: 120, SubGroupName: "Role Definition and Access Config Studio", DisplayOrder: 4, GroupCode: 60 },
    { SubGroupCode: 121, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 61 },
    { SubGroupCode: 122, SubGroupName: "Web Service Integration", DisplayOrder: 17, GroupCode: 62 },
    { SubGroupCode: 123, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 63 },
    { SubGroupCode: 124, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 64 },
    { SubGroupCode: 125, SubGroupName: "Training Plan Process Studio", DisplayOrder: 2, GroupCode: 64 },
    { SubGroupCode: 126, SubGroupName: "Analytics Studio", DisplayOrder: 3, GroupCode: 64 },
    { SubGroupCode: 127, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 65 },
    { SubGroupCode: 128, SubGroupName: "Process Studio", DisplayOrder: 2, GroupCode: 65 },
    { SubGroupCode: 129, SubGroupName: "Analytics Studio", DisplayOrder: 4, GroupCode: 65 },
    { SubGroupCode: 130, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 66 },
    { SubGroupCode: 131, SubGroupName: "Course Material", DisplayOrder: 2, GroupCode: 66 },
    { SubGroupCode: 132, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 67 },
    { SubGroupCode: 133, SubGroupName: "Evaluation Process Studio", DisplayOrder: 2, GroupCode: 68 },
    { SubGroupCode: 134, SubGroupName: "Analytics Studio", DisplayOrder: 3, GroupCode: 68 },
    { SubGroupCode: 135, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 69 },
    { SubGroupCode: 136, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 70 },
    { SubGroupCode: 137, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 71 },
    { SubGroupCode: 138, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 72 },
    { SubGroupCode: 139, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 73 },
    { SubGroupCode: 140, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 74 },
    { SubGroupCode: 141, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 75 },
    { SubGroupCode: 142, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 76 },
    { SubGroupCode: 143, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 77 },
    { SubGroupCode: 144, SubGroupName: "Analytics Studio", DisplayOrder: 3, GroupCode: 78 },
    { SubGroupCode: 145, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 79 },
    { SubGroupCode: 146, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 80 },
    { SubGroupCode: 147, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 81 },
    { SubGroupCode: 148, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 82 },
    { SubGroupCode: 149, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 83 },
    { SubGroupCode: 150, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 84 },
    { SubGroupCode: 151, SubGroupName: "Rostering Studio", DisplayOrder: 2, GroupCode: 84 },
    { SubGroupCode: 152, SubGroupName: "Analytics Studio", DisplayOrder: 5, GroupCode: 84 },
    { SubGroupCode: 153, SubGroupName: "Imports", DisplayOrder: 4, GroupCode: 84 },
    { SubGroupCode: 154, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 85 },
    { SubGroupCode: 155, SubGroupName: "Attendance Process Studio", DisplayOrder: 2, GroupCode: 85 },
    { SubGroupCode: 156, SubGroupName: "Attendance Process Studio", DisplayOrder: 2, GroupCode: 85 },
    { SubGroupCode: 157, SubGroupName: "Analytics Studio", DisplayOrder: 4, GroupCode: 85 },
    { SubGroupCode: 158, SubGroupName: "Imports", DisplayOrder: 3, GroupCode: 85 },
    { SubGroupCode: 159, SubGroupName: "Handoff Analytics Studio", DisplayOrder: 5, GroupCode: 85 },
    { SubGroupCode: 160, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 86 },
    { SubGroupCode: 161, SubGroupName: "Regularization Process Studio", DisplayOrder: 2, GroupCode: 86 },
    { SubGroupCode: 162, SubGroupName: "Utilities Studio", DisplayOrder: 3, GroupCode: 86 },
    { SubGroupCode: 163, SubGroupName: "Analytics Studio", DisplayOrder: 4, GroupCode: 86 },
    { SubGroupCode: 164, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 87 },
    { SubGroupCode: 165, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 88 },
    { SubGroupCode: 166, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 89 },
    { SubGroupCode: 167, SubGroupName: "Reports", DisplayOrder: 3, GroupCode: 90 },
    { SubGroupCode: 168, SubGroupName: "Reports", DisplayOrder: 3, GroupCode: 91 },
    { SubGroupCode: 169, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 92 },
    { SubGroupCode: 170, SubGroupName: "Leave Process Studio", DisplayOrder: 2, GroupCode: 92 },
    { SubGroupCode: 171, SubGroupName: "Analytics Studio", DisplayOrder: 6, GroupCode: 92 },
    { SubGroupCode: 172, SubGroupName: "Reports", DisplayOrder: 3, GroupCode: 93 },
    { SubGroupCode: 176, SubGroupName: "Challan Process", DisplayOrder: 30, GroupCode: 97 },
    { SubGroupCode: 177, SubGroupName: "Maker Inputs", DisplayOrder: 10, GroupCode: 98 },
    { SubGroupCode: 178, SubGroupName: "Analytics", DisplayOrder: 5, GroupCode: 99 },
    { SubGroupCode: 179, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 99 },
    { SubGroupCode: 180, SubGroupName: "Imports", DisplayOrder: 3, GroupCode: 99 },
    { SubGroupCode: 181, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 100 },
    { SubGroupCode: 182, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 100 },
    { SubGroupCode: 183, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 101 },
    { SubGroupCode: 184, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 102 },
    { SubGroupCode: 185, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 103 },
    { SubGroupCode: 186, SubGroupName: "Utilities", DisplayOrder: 0, GroupCode: 104 },
    { SubGroupCode: 187, SubGroupName: "Abstracts", DisplayOrder: 1, GroupCode: 104 },
    { SubGroupCode: 188, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 105 },
    { SubGroupCode: 189, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 106 },
    { SubGroupCode: 190, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 107 },
    { SubGroupCode: 191, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 108 },
    { SubGroupCode: 192, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 108 },
    { SubGroupCode: 193, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 109 },
    { SubGroupCode: 194, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 110 },
    { SubGroupCode: 195, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 111 },
    { SubGroupCode: 196, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 112 },
    { SubGroupCode: 197, SubGroupName: "Reports", DisplayOrder: 3, GroupCode: 113 },
    { SubGroupCode: 198, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 114 },
    { SubGroupCode: 199, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 115 },
    { SubGroupCode: 200, SubGroupName: "Travel Claim Process Studio", DisplayOrder: 4, GroupCode: 115 },
    { SubGroupCode: 201, SubGroupName: "Analytics Studio", DisplayOrder: 5, GroupCode: 115 },
    { SubGroupCode: 202, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 116 },
    { SubGroupCode: 203, SubGroupName: "Travel Request Process Studio", DisplayOrder: 2, GroupCode: 116 },
    { SubGroupCode: 204, SubGroupName: "Travel Booking Analytics Studio", DisplayOrder: 5, GroupCode: 116 },
    { SubGroupCode: 205, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 117 },
    { SubGroupCode: 206, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 118 },
    { SubGroupCode: 207, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 119 },
    { SubGroupCode: 208, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 120 },
    { SubGroupCode: 209, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 121 },
    { SubGroupCode: 210, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 122 },
    { SubGroupCode: 211, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 122 },
    { SubGroupCode: 212, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 123 },
    { SubGroupCode: 213, SubGroupName: "Expense Process Studio", DisplayOrder: 8, GroupCode: 123 },
    { SubGroupCode: 214, SubGroupName: "Analytics Studio", DisplayOrder: 10, GroupCode: 123 },
    { SubGroupCode: 215, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 124 },
    { SubGroupCode: 216, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 125 },
    { SubGroupCode: 217, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 126 },
    { SubGroupCode: 218, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 127 },
    { SubGroupCode: 219, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 128 },
    { SubGroupCode: 220, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 129 },
    { SubGroupCode: 221, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 130 },
    { SubGroupCode: 222, SubGroupName: "Idea Hub", DisplayOrder: 1, GroupCode: 131 },
    { SubGroupCode: 223, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 132 },
    { SubGroupCode: 224, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 133 },
    { SubGroupCode: 225, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 134 },
    { SubGroupCode: 226, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 134 },
    { SubGroupCode: 227, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 134 },
    { SubGroupCode: 228, SubGroupName: "Assessment Config Studio", DisplayOrder: 1, GroupCode: 135 },
    { SubGroupCode: 229, SubGroupName: "Analytics Studio", DisplayOrder: 5, GroupCode: 135 },
    { SubGroupCode: 230, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 136 },
    { SubGroupCode: 231, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 137 },
    { SubGroupCode: 232, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 137 },
    { SubGroupCode: 233, SubGroupName: "Content", DisplayOrder: 1, GroupCode: 138 },
    { SubGroupCode: 234, SubGroupName: "Gallery", DisplayOrder: 2, GroupCode: 138 },
    { SubGroupCode: 235, SubGroupName: "Poll", DisplayOrder: 3, GroupCode: 138 },
    { SubGroupCode: 236, SubGroupName: "Idea Management", DisplayOrder: 6, GroupCode: 138 },
    { SubGroupCode: 237, SubGroupName: "Greetings", DisplayOrder: 4, GroupCode: 138 },
    { SubGroupCode: 238, SubGroupName: "Blog", DisplayOrder: 5, GroupCode: 138 },
    { SubGroupCode: 239, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 139 },
    { SubGroupCode: 240, SubGroupName: "HR Documents", DisplayOrder: 15, GroupCode: 139 },
    { SubGroupCode: 241, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 140 },
    { SubGroupCode: 242, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 141 },
    { SubGroupCode: 243, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 142 },
    { SubGroupCode: 244, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 143 },
    { SubGroupCode: 245, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 144 },
    { SubGroupCode: 246, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 145 },
    { SubGroupCode: 247, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 145 },
    { SubGroupCode: 248, SubGroupName: "Reports", DisplayOrder: 3, GroupCode: 146 },
    { SubGroupCode: 249, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 147 },
    { SubGroupCode: 250, SubGroupName: "Masters", DisplayOrder: 1, GroupCode: 148 },
    { SubGroupCode: 251, SubGroupName: "Utilities", DisplayOrder: 2, GroupCode: 149 },
    { SubGroupCode: 252, SubGroupName: "Imports", DisplayOrder: 40, GroupCode: 154 },
    { SubGroupCode: 253, SubGroupName: "Checker Approvals", DisplayOrder: 20, GroupCode: 98 },
    { SubGroupCode: 254, SubGroupName: "Salary Process", DisplayOrder: 60, GroupCode: 155 },
    { SubGroupCode: 255, SubGroupName: "Tax Process", DisplayOrder: 0, GroupCode: 155 },
    { SubGroupCode: 256, SubGroupName: "Confirm Process", DisplayOrder: 700, GroupCode: 155 },
    { SubGroupCode: 257, SubGroupName: "Loan", DisplayOrder: 10, GroupCode: 155 },
    { SubGroupCode: 258, SubGroupName: "Configuration Studio", DisplayOrder: 10, GroupCode: 155 },
    { SubGroupCode: 259, SubGroupName: "Imports", DisplayOrder: 40, GroupCode: 155 },
    { SubGroupCode: 260, SubGroupName: "Salary Inputs", DisplayOrder: 20, GroupCode: 155 },
    { SubGroupCode: 261, SubGroupName: "Salary Analytics", DisplayOrder: 70, GroupCode: 155 },
    { SubGroupCode: 262, SubGroupName: "Statutory Reports", DisplayOrder: 600, GroupCode: 155 },
    { SubGroupCode: 263, SubGroupName: "HR Service Desk", DisplayOrder: 2, GroupCode: 156 },
    { SubGroupCode: 264, SubGroupName: "Preparatory Process", DisplayOrder: 30, GroupCode: 154 },
    { SubGroupCode: 265, SubGroupName: "Closure Process", DisplayOrder: 20, GroupCode: 97 },
    { SubGroupCode: 266, SubGroupName: "Salary", DisplayOrder: 0, GroupCode: 155 },
    { SubGroupCode: 267, SubGroupName: "Tax Inputs", DisplayOrder: 30, GroupCode: 155 },
    { SubGroupCode: 268, SubGroupName: "Statutory Abstracts", DisplayOrder: 40, GroupCode: 97 },
    { SubGroupCode: 269, SubGroupName: "Analytics", DisplayOrder: 50, GroupCode: 154 },
    { SubGroupCode: 270, SubGroupName: "Travel Booking Process Studio", DisplayOrder: 3, GroupCode: 116 },
    { SubGroupCode: 271, SubGroupName: "Travel Request Analytics Studio", DisplayOrder: 4, GroupCode: 116 },
    { SubGroupCode: 272, SubGroupName: "Imports", DisplayOrder: 3, GroupCode: 65 },
    { SubGroupCode: 273, SubGroupName: "Payroll Process Studio", DisplayOrder: 1, GroupCode: 157 },
    { SubGroupCode: 274, SubGroupName: "Handoff Analytics Studio", DisplayOrder: 2, GroupCode: 157 },
    { SubGroupCode: 275, SubGroupName: "CTC Process", DisplayOrder: 20, GroupCode: 154 },
    { SubGroupCode: 276, SubGroupName: "Configuration Studio", DisplayOrder: 10, GroupCode: 154 },
    { SubGroupCode: 277, SubGroupName: "Tax Analytics", DisplayOrder: 80, GroupCode: 155 },
    { SubGroupCode: 278, SubGroupName: "Investment Configuration Studio", DisplayOrder: 25, GroupCode: 155 },
    { SubGroupCode: 279, SubGroupName: "Course Fee Reimbursement", DisplayOrder: 5, GroupCode: 37 },
    { SubGroupCode: 280, SubGroupName: "General Configuration", DisplayOrder: 1, GroupCode: 158 },
    { SubGroupCode: 281, SubGroupName: "Menu Configuration", DisplayOrder: 2, GroupCode: 158 },
    { SubGroupCode: 282, SubGroupName: "Security Configuration", DisplayOrder: 3, GroupCode: 158 },
    { SubGroupCode: 283, SubGroupName: "Attendance & Time off", DisplayOrder: 5, GroupCode: 158 },
    { SubGroupCode: 284, SubGroupName: "Workforce Management", DisplayOrder: 7, GroupCode: 158 },
    { SubGroupCode: 285, SubGroupName: "Travel Management", DisplayOrder: 7, GroupCode: 158 },
    { SubGroupCode: 286, SubGroupName: "Expenses Management", DisplayOrder: 8, GroupCode: 158 },
    { SubGroupCode: 287, SubGroupName: "Workflow", DisplayOrder: 1, GroupCode: 159 },
    { SubGroupCode: 288, SubGroupName: "Workforce Analytics", DisplayOrder: 31, GroupCode: 158 },
    { SubGroupCode: 289, SubGroupName: "Talent Acquisition", DisplayOrder: 4, GroupCode: 158 },
    { SubGroupCode: 290, SubGroupName: "Talent Acquisition", DisplayOrder: 1, GroupCode: 159 },
    { SubGroupCode: 291, SubGroupName: "Workforce Management", DisplayOrder: 1, GroupCode: 159 },
    { SubGroupCode: 292, SubGroupName: "Travel & Expenses", DisplayOrder: 7, GroupCode: 159 },
    { SubGroupCode: 293, SubGroupName: "Mail", DisplayOrder: 2, GroupCode: 131 },
    { SubGroupCode: 294, SubGroupName: "Abstracts", DisplayOrder: 3, GroupCode: 131 },
    { SubGroupCode: 295, SubGroupName: "Performance and Goals", DisplayOrder: 11, GroupCode: 158 },
    { SubGroupCode: 296, SubGroupName: "Pre-Employment Verification", DisplayOrder: 2, GroupCode: 23 },
    { SubGroupCode: 297, SubGroupName: "Post Offer Process", DisplayOrder: 1, GroupCode: 26 },
    { SubGroupCode: 298, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 160 },
    { SubGroupCode: 299, SubGroupName: "Process Studio", DisplayOrder: 2, GroupCode: 160 },
    { SubGroupCode: 300, SubGroupName: "Imports", DisplayOrder: 3, GroupCode: 160 },
    { SubGroupCode: 301, SubGroupName: "Local Conveyance Configuration", DisplayOrder: 4, GroupCode: 123 },
    { SubGroupCode: 302, SubGroupName: "Project Configuration", DisplayOrder: 6, GroupCode: 123 },
    { SubGroupCode: 303, SubGroupName: "Configuration Studio", DisplayOrder: 10, GroupCode: 97 },
    { SubGroupCode: 304, SubGroupName: "Reimbursement Process", DisplayOrder: 35, GroupCode: 155 },
    { SubGroupCode: 305, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 134 },
    { SubGroupCode: 306, SubGroupName: "Terms & Conditions", DisplayOrder: 2, GroupCode: 139 },
    { SubGroupCode: 307, SubGroupName: "Survey Config Studio", DisplayOrder: 3, GroupCode: 135 },
    { SubGroupCode: 308, SubGroupName: "Survey", DisplayOrder: 4, GroupCode: 135 },
    { SubGroupCode: 309, SubGroupName: "Imports", DisplayOrder: 3, GroupCode: 35 },
    { SubGroupCode: 310, SubGroupName: "Bonus & Advance", DisplayOrder: 3, GroupCode: 30 },
    { SubGroupCode: 311, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 99 },
    { SubGroupCode: 312, SubGroupName: "Compensation Review Process", DisplayOrder: 2, GroupCode: 99 },
    { SubGroupCode: 313, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 162 },
    { SubGroupCode: 314, SubGroupName: "Define Process & Configure Wizards", DisplayOrder: 3, GroupCode: 158 },
    { SubGroupCode: 315, SubGroupName: "Enterprise Setup Configuration", DisplayOrder: 2, GroupCode: 158 },
    { SubGroupCode: 316, SubGroupName: "Mail Configuration", DisplayOrder: 4, GroupCode: 158 },
    { SubGroupCode: 317, SubGroupName: "Separation Documents Studio", DisplayOrder: 4, GroupCode: 52 },
    { SubGroupCode: 318, SubGroupName: "Resignation Workflow Process Studio", DisplayOrder: 30, GroupCode: 52 },
    { SubGroupCode: 319, SubGroupName: "Absconding / Termination / Suspension Process Studio", DisplayOrder: 40, GroupCode: 52 },
    { SubGroupCode: 320, SubGroupName: "Separation Checklist Process Studio", DisplayOrder: 50, GroupCode: 52 },
    { SubGroupCode: 321, SubGroupName: "Separation Interview Form Process Studio", DisplayOrder: 60, GroupCode: 52 },
    { SubGroupCode: 322, SubGroupName: "Loan Subsidy", DisplayOrder: 4, GroupCode: 37 },
    { SubGroupCode: 323, SubGroupName: "Loan Subsidy", DisplayOrder: 20, GroupCode: 701 },
    { SubGroupCode: 324, SubGroupName: "My Sphere's Onboarding Feedback", DisplayOrder: 5, GroupCode: 703 },
    { SubGroupCode: 325, SubGroupName: "Relative Info", DisplayOrder: 10, GroupCode: 701 },
    { SubGroupCode: 326, SubGroupName: "My Team's Relative Info", DisplayOrder: 10, GroupCode: 702 },
    { SubGroupCode: 333, SubGroupName: "Loan Process", DisplayOrder: 9, GroupCode: 123 },
    { SubGroupCode: 334, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 163 },
    { SubGroupCode: 335, SubGroupName: "Attendance Certification Process Studio", DisplayOrder: 2, GroupCode: 85 },
    { SubGroupCode: 339, SubGroupName: "R and R Process", DisplayOrder: 7, GroupCode: 717 },
    { SubGroupCode: 340, SubGroupName: "R and R Process", DisplayOrder: 7, GroupCode: 717 },
    { SubGroupCode: 341, SubGroupName: "Vacant Abstract", DisplayOrder: 10, GroupCode: 40 },
    { SubGroupCode: 342, SubGroupName: "Norminee Info", DisplayOrder: 4, GroupCode: 37 },
    { SubGroupCode: 400, SubGroupName: "BGV Process", DisplayOrder: 200, GroupCode: 721 },
    { SubGroupCode: 401, SubGroupName: "LTFS - SEBI Report", DisplayOrder: 7, GroupCode: 37 },
    { SubGroupCode: 500, SubGroupName: "Org Structure", DisplayOrder: 1, GroupCode: 161 },
    { SubGroupCode: 501, SubGroupName: "Vacancy", DisplayOrder: 2, GroupCode: 161 },
    { SubGroupCode: 502, SubGroupName: "Org & Vacancy Abstract", DisplayOrder: 5, GroupCode: 161 },
    { SubGroupCode: 503, SubGroupName: "Imports", DisplayOrder: 4, GroupCode: 161 },
    { SubGroupCode: 504, SubGroupName: "Analytics Studio", DisplayOrder: 12, GroupCode: 138 },
    { SubGroupCode: 505, SubGroupName: "Journal Voucher Process", DisplayOrder: 25, GroupCode: 97 },
    { SubGroupCode: 506, SubGroupName: "Maker Checker Analytics", DisplayOrder: 30, GroupCode: 98 },
    { SubGroupCode: 507, SubGroupName: "Maker Imports", DisplayOrder: 15, GroupCode: 98 },
    { SubGroupCode: 508, SubGroupName: "Configuration & Audit Reports", DisplayOrder: 60, GroupCode: 97 },
    { SubGroupCode: 509, SubGroupName: "Utilities", DisplayOrder: 40, GroupCode: 97 },
    { SubGroupCode: 510, SubGroupName: "External Interfacing", DisplayOrder: 0, GroupCode: 97 },
    { SubGroupCode: 511, SubGroupName: "Process Studio", DisplayOrder: 10, GroupCode: 782 },
    { SubGroupCode: 512, SubGroupName: "Open API Documentation", DisplayOrder: 15, GroupCode: 158 },
    { SubGroupCode: 513, SubGroupName: "Business Process", DisplayOrder: 10, GroupCode: 159 },
    { SubGroupCode: 514, SubGroupName: "My Sphere's Onboarding Feedback", DisplayOrder: 2, GroupCode: 703 },
    { SubGroupCode: 515, SubGroupName: "Process Studio", DisplayOrder: 10, GroupCode: 797 },
    { SubGroupCode: 516, SubGroupName: "Configuration Studio", DisplayOrder: 40, GroupCode: 164 },
    { SubGroupCode: 517, SubGroupName: "Process Studio", DisplayOrder: 40, GroupCode: 164 },
    { SubGroupCode: 518, SubGroupName: "Imports", DisplayOrder: 50, GroupCode: 164 },
    { SubGroupCode: 519, SubGroupName: "Analytics", DisplayOrder: 60, GroupCode: 164 },
    { SubGroupCode: 520, SubGroupName: "Analytics Studio", DisplayOrder: 160, GroupCode: 805 },
    { SubGroupCode: 526, SubGroupName: "Imports", DisplayOrder: 30, GroupCode: 166 },
    { SubGroupCode: 527, SubGroupName: "Configuration", DisplayOrder: 5, GroupCode: 510 },
    { SubGroupCode: 528, SubGroupName: "Imports", DisplayOrder: 30, GroupCode: 510 },
    { SubGroupCode: 529, SubGroupName: "Analytics Studio", DisplayOrder: 40, GroupCode: 510 },
    { SubGroupCode: 530, SubGroupName: "Process Studio", DisplayOrder: 5, GroupCode: 510 },
    { SubGroupCode: 531, SubGroupName: "Configuration", DisplayOrder: 5, GroupCode: 511 },
    { SubGroupCode: 532, SubGroupName: "Analytics Studio", DisplayOrder: 40, GroupCode: 511 },
    { SubGroupCode: 533, SubGroupName: "Imports", DisplayOrder: 5, GroupCode: 511 },
    { SubGroupCode: 534, SubGroupName: "Process Studio", DisplayOrder: 5, GroupCode: 511 },
    { SubGroupCode: 535, SubGroupName: "Workline Hub", DisplayOrder: 10, GroupCode: 511 },
    { SubGroupCode: 701, SubGroupName: "My Profile", DisplayOrder: 1, GroupCode: 701 },
    { SubGroupCode: 702, SubGroupName: "Manager Change Request", DisplayOrder: 2, GroupCode: 701 },
    { SubGroupCode: 703, SubGroupName: "My Documents", DisplayOrder: 3, GroupCode: 701 },
    { SubGroupCode: 704, SubGroupName: "My Letters", DisplayOrder: 4, GroupCode: 701 },
    { SubGroupCode: 705, SubGroupName: "Onboarding", DisplayOrder: 5, GroupCode: 701 },
    { SubGroupCode: 706, SubGroupName: "My Confirmation Appraisal", DisplayOrder: 6, GroupCode: 701 },
    { SubGroupCode: 707, SubGroupName: "My Separation Process", DisplayOrder: 7, GroupCode: 701 },
    { SubGroupCode: 708, SubGroupName: "My Separation Interview", DisplayOrder: 8, GroupCode: 701 },
    { SubGroupCode: 709, SubGroupName: "View My Clearance Checklist", DisplayOrder: 9, GroupCode: 701 },
    { SubGroupCode: 710, SubGroupName: "My Team's Profile", DisplayOrder: 10, GroupCode: 702 },
    { SubGroupCode: 711, SubGroupName: "My Team's Onboarding Feedback", DisplayOrder: 11, GroupCode: 702 },
    { SubGroupCode: 712, SubGroupName: "My Team's Manager Change Request", DisplayOrder: 13, GroupCode: 702 },
    { SubGroupCode: 713, SubGroupName: "My Team's Movement Request", DisplayOrder: 14, GroupCode: 702 },
    { SubGroupCode: 714, SubGroupName: "My Team's Confirmation Appraisal", DisplayOrder: 15, GroupCode: 702 },
    { SubGroupCode: 715, SubGroupName: "My Team's Reports", DisplayOrder: 15, GroupCode: 702 },
    { SubGroupCode: 716, SubGroupName: "My Team's Separation Process", DisplayOrder: 16, GroupCode: 702 },
    { SubGroupCode: 717, SubGroupName: "My Team's Absconding / Termination List", DisplayOrder: 17, GroupCode: 702 },
    { SubGroupCode: 718, SubGroupName: "My Team's Separation Interview", DisplayOrder: 18, GroupCode: 702 },
    { SubGroupCode: 719, SubGroupName: "My Team's Clearance Checklist", DisplayOrder: 19, GroupCode: 702 },
    { SubGroupCode: 720, SubGroupName: "My Sphere's Profile", DisplayOrder: 1, GroupCode: 703 },
    { SubGroupCode: 721, SubGroupName: "My Sphere's Movement Request", DisplayOrder: 2, GroupCode: 703 },
    { SubGroupCode: 722, SubGroupName: "My Sphere's Confirmation Appraisal", DisplayOrder: 3, GroupCode: 703 },
    { SubGroupCode: 723, SubGroupName: "My Sphere's Manager Change Request", DisplayOrder: 4, GroupCode: 703 },
    { SubGroupCode: 724, SubGroupName: "My Sphere's Separation Process", DisplayOrder: 5, GroupCode: 703 },
    { SubGroupCode: 725, SubGroupName: "My Sphere's Absconding / Termination List", DisplayOrder: 6, GroupCode: 703 },
    { SubGroupCode: 726, SubGroupName: "My Sphere's Separation Interview", DisplayOrder: 7, GroupCode: 703 },
    { SubGroupCode: 727, SubGroupName: "My Sphere's Clearance Checklist", DisplayOrder: 8, GroupCode: 703 },
    { SubGroupCode: 728, SubGroupName: "Airfare", DisplayOrder: 10, GroupCode: 701 },
    { SubGroupCode: 729, SubGroupName: "My Team's Team Validation", DisplayOrder: 16, GroupCode: 702 },
    { SubGroupCode: 730, SubGroupName: "My Time Card", DisplayOrder: 1, GroupCode: 723 },
    { SubGroupCode: 731, SubGroupName: "Salary Advance Process", DisplayOrder: 1, GroupCode: 702 },
    { SubGroupCode: 732, SubGroupName: "Salary Advance Process", DisplayOrder: 1, GroupCode: 703 },
    { SubGroupCode: 761, SubGroupName: "Leave Process", DisplayOrder: 1, GroupCode: 707 },
    { SubGroupCode: 762, SubGroupName: "Regularization Process", DisplayOrder: 2, GroupCode: 707 },
    { SubGroupCode: 763, SubGroupName: "View Roster & Attendance", DisplayOrder: 4, GroupCode: 707 },
    { SubGroupCode: 764, SubGroupName: "Delegate - Approval", DisplayOrder: 6, GroupCode: 707 },
    { SubGroupCode: 765, SubGroupName: "Update Roster & Attendance", DisplayOrder: 8, GroupCode: 708 },
    { SubGroupCode: 766, SubGroupName: "Upload Roster & Attendance", DisplayOrder: 9, GroupCode: 708 },
    { SubGroupCode: 767, SubGroupName: "Approval Process", DisplayOrder: 7, GroupCode: 708 },
    { SubGroupCode: 768, SubGroupName: "Team's Reports", DisplayOrder: 10, GroupCode: 708 },
    { SubGroupCode: 769, SubGroupName: "Leave Reports", DisplayOrder: 11, GroupCode: 708 },
    { SubGroupCode: 770, SubGroupName: "Reimbursement", DisplayOrder: 1, GroupCode: 710 },
    { SubGroupCode: 771, SubGroupName: "Payroll", DisplayOrder: 1, GroupCode: 710 },
    { SubGroupCode: 772, SubGroupName: "Reimbursement", DisplayOrder: 1, GroupCode: 713 },
    { SubGroupCode: 773, SubGroupName: "Reimbursement", DisplayOrder: 1, GroupCode: 714 },
    { SubGroupCode: 774, SubGroupName: "Travel Request & Claim", DisplayOrder: 1, GroupCode: 715 },
    { SubGroupCode: 775, SubGroupName: "Travel Approval", DisplayOrder: 1, GroupCode: 716 },
    { SubGroupCode: 776, SubGroupName: "Goals and Appraisal", DisplayOrder: 1, GroupCode: 717 },
    { SubGroupCode: 777, SubGroupName: "Goals and Appraisal", DisplayOrder: 1, GroupCode: 718 },
    { SubGroupCode: 778, SubGroupName: "Goals and Appraisal", DisplayOrder: 1, GroupCode: 719 },
    { SubGroupCode: 779, SubGroupName: "Delegation Manager", DisplayOrder: 2, GroupCode: 717 },
    { SubGroupCode: 780, SubGroupName: "Talent Acquisition", DisplayOrder: 1, GroupCode: 720 },
    { SubGroupCode: 781, SubGroupName: "Manpower Requisition Form", DisplayOrder: 1, GroupCode: 721 },
    { SubGroupCode: 782, SubGroupName: "Screening Process", DisplayOrder: 2, GroupCode: 721 },
    { SubGroupCode: 783, SubGroupName: "Interview Process", DisplayOrder: 3, GroupCode: 721 },
    { SubGroupCode: 784, SubGroupName: "360&deg; Feedback", DisplayOrder: 3, GroupCode: 717 },
    { SubGroupCode: 785, SubGroupName: "360 Degree Feedback", DisplayOrder: 3, GroupCode: 718 },
    { SubGroupCode: 786, SubGroupName: "<h3 class=\"box-title\">Training</h3>", DisplayOrder: 1, GroupCode: 750 },
    { SubGroupCode: 787, SubGroupName: "Training", DisplayOrder: 1, GroupCode: 751 },
    { SubGroupCode: 788, SubGroupName: "Compensation Review", DisplayOrder: 3, GroupCode: 718 },
    { SubGroupCode: 789, SubGroupName: "Enterprise Configuration", DisplayOrder: 3, GroupCode: 158 },
    { SubGroupCode: 790, SubGroupName: "Survey & Assessment", DisplayOrder: 5, GroupCode: 723 },
    { SubGroupCode: 791, SubGroupName: "Workforce Engagement", DisplayOrder: 12, GroupCode: 158 },
    { SubGroupCode: 792, SubGroupName: "Delegate User Mapping", DisplayOrder: 12, GroupCode: 708 },
    { SubGroupCode: 793, SubGroupName: "My Team's Asset Allocation", DisplayOrder: 12, GroupCode: 702 },
    { SubGroupCode: 794, SubGroupName: "My Sphere's Asset Allocation", DisplayOrder: 2, GroupCode: 703 },
    { SubGroupCode: 795, SubGroupName: "Document Upload", DisplayOrder: 4, GroupCode: 721 },
    { SubGroupCode: 796, SubGroupName: "Knowledge Base", DisplayOrder: 3, GroupCode: 723 },
    { SubGroupCode: 797, SubGroupName: "Collobaration", DisplayOrder: 3, GroupCode: 723 },
    { SubGroupCode: 798, SubGroupName: "Update Roster & Attendance", DisplayOrder: 8, GroupCode: 709 },
    { SubGroupCode: 799, SubGroupName: "Upload Roster & Attendance", DisplayOrder: 9, GroupCode: 709 },
    { SubGroupCode: 800, SubGroupName: "Approval Process", DisplayOrder: 7, GroupCode: 709 },
    { SubGroupCode: 801, SubGroupName: "Team's Reports", DisplayOrder: 10, GroupCode: 709 },
    { SubGroupCode: 802, SubGroupName: "Leave Reports", DisplayOrder: 11, GroupCode: 709 },
    { SubGroupCode: 803, SubGroupName: "Delegate User Mapping", DisplayOrder: 12, GroupCode: 709 },
    { SubGroupCode: 804, SubGroupName: "Custom Abstract Group 2", DisplayOrder: 30, GroupCode: 5 },
    { SubGroupCode: 805, SubGroupName: "OKR", DisplayOrder: 31, GroupCode: 5 },
    { SubGroupCode: 806, SubGroupName: "OKR", DisplayOrder: 2, GroupCode: 718 },
    { SubGroupCode: 815, SubGroupName: "Assessment", DisplayOrder: 2, GroupCode: 135 },
    { SubGroupCode: 816, SubGroupName: "Survey", DisplayOrder: 4, GroupCode: 135 },
    { SubGroupCode: 817, SubGroupName: "Performance Diary", DisplayOrder: 5, GroupCode: 717 },
    { SubGroupCode: 818, SubGroupName: "Performance Diary", DisplayOrder: 5, GroupCode: 718 },
    { SubGroupCode: 819, SubGroupName: "Profile Management", DisplayOrder: 5, GroupCode: 159 },
    { SubGroupCode: 820, SubGroupName: "Slack", DisplayOrder: 13, GroupCode: 158 },
    { SubGroupCode: 821, SubGroupName: "Post Joining Verification", DisplayOrder: 2, GroupCode: 26 },
    { SubGroupCode: 822, SubGroupName: "Letters", DisplayOrder: 3, GroupCode: 2 },
    { SubGroupCode: 823, SubGroupName: "Letters", DisplayOrder: 6, GroupCode: 717 },
    { SubGroupCode: 824, SubGroupName: "ESOP / RSU Process", DisplayOrder: 1, GroupCode: 101 },
    { SubGroupCode: 825, SubGroupName: "Imports", DisplayOrder: 2, GroupCode: 101 },
    { SubGroupCode: 826, SubGroupName: "Analytics Studio", DisplayOrder: 3, GroupCode: 101 },
    { SubGroupCode: 827, SubGroupName: "ESOP/RSU", DisplayOrder: 3, GroupCode: 710 },
    { SubGroupCode: 828, SubGroupName: "Custom Review", DisplayOrder: 12, GroupCode: 5 },
    { SubGroupCode: 829, SubGroupName: "Standard KRA", DisplayOrder: 5, GroupCode: 4 },
    { SubGroupCode: 830, SubGroupName: "Review Process", DisplayOrder: 6, GroupCode: 5 },
    { SubGroupCode: 831, SubGroupName: "Review Imports", DisplayOrder: 10, GroupCode: 5 },
    { SubGroupCode: 832, SubGroupName: "Review Abstracts", DisplayOrder: 18, GroupCode: 5 },
    { SubGroupCode: 833, SubGroupName: "Forms", DisplayOrder: 1, GroupCode: 754 },
    { SubGroupCode: 834, SubGroupName: "Training & Development", DisplayOrder: 8, GroupCode: 159 },
    { SubGroupCode: 835, SubGroupName: "Compensation & Benefits", DisplayOrder: 13, GroupCode: 158 },
    { SubGroupCode: 836, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 755 },
    { SubGroupCode: 837, SubGroupName: "Configuration Studio", DisplayOrder: 1, GroupCode: 756 },
    { SubGroupCode: 838, SubGroupName: "Bonus & Advance Abstract", DisplayOrder: 5, GroupCode: 30 },
    { SubGroupCode: 839, SubGroupName: "Timesheet", DisplayOrder: 1, GroupCode: 724 },
    { SubGroupCode: 841, SubGroupName: "Analytics Studio", DisplayOrder: 1, GroupCode: 756 },
    { SubGroupCode: 842, SubGroupName: "Process Studio", DisplayOrder: 20, GroupCode: 755 },
    { SubGroupCode: 843, SubGroupName: "Imports", DisplayOrder: 25, GroupCode: 755 },
    { SubGroupCode: 844, SubGroupName: "Analytics Studio", DisplayOrder: 30, GroupCode: 755 },
    { SubGroupCode: 845, SubGroupName: "My Time Card", DisplayOrder: 2, GroupCode: 723 },
    { SubGroupCode: 846, SubGroupName: "Payroll", DisplayOrder: 1, GroupCode: 711 },
    { SubGroupCode: 847, SubGroupName: "Loan", DisplayOrder: 4, GroupCode: 710 },
    { SubGroupCode: 848, SubGroupName: "Office Utillities", DisplayOrder: 3, GroupCode: 37 },
    { SubGroupCode: 849, SubGroupName: "Office Utillities", DisplayOrder: 3, GroupCode: 701 },
    { SubGroupCode: 850, SubGroupName: "Travel Reset Studio", DisplayOrder: 3, GroupCode: 116 },
    { SubGroupCode: 851, SubGroupName: "Forms", DisplayOrder: 3, GroupCode: 701 },
    { SubGroupCode: 853, SubGroupName: "Workforce Loan Status", DisplayOrder: 2, GroupCode: 711 },
    { SubGroupCode: 854, SubGroupName: "Reimbursement", DisplayOrder: 1, GroupCode: 757 },
    { SubGroupCode: 855, SubGroupName: "HR Advance", DisplayOrder: 4, GroupCode: 701 },
    { SubGroupCode: 856, SubGroupName: "Pre-Boarding", DisplayOrder: 2, GroupCode: 30 },
    { SubGroupCode: 857, SubGroupName: "HR Advance", DisplayOrder: 4, GroupCode: 37 },
    { SubGroupCode: 858, SubGroupName: "My Team's Salary Advance", DisplayOrder: 15, GroupCode: 702 },
    { SubGroupCode: 859, SubGroupName: "My Sphere's Salary Advance", DisplayOrder: 6, GroupCode: 703 },
    { SubGroupCode: 860, SubGroupName: "My Team's Contract Renewal", DisplayOrder: 15, GroupCode: 702 },
    { SubGroupCode: 861, SubGroupName: "My Sphere's Contract Renewal", DisplayOrder: 15, GroupCode: 703 },
    { SubGroupCode: 862, SubGroupName: "HR Diary", DisplayOrder: 8, GroupCode: 14 },
    { SubGroupCode: 863, SubGroupName: "Resources", DisplayOrder: 5, GroupCode: 718 },
    { SubGroupCode: 864, SubGroupName: "Resources", DisplayOrder: 5, GroupCode: 717 },
    { SubGroupCode: 865, SubGroupName: "Resources", DisplayOrder: 3, GroupCode: 719 },
    { SubGroupCode: 866, SubGroupName: "Resources", DisplayOrder: 5, GroupCode: 718 },
    { SubGroupCode: 867, SubGroupName: "Check In", DisplayOrder: 2, GroupCode: 719 },
    { SubGroupCode: 887, SubGroupName: "Travel View", DisplayOrder: 2, GroupCode: 775 },
    { SubGroupCode: 888, SubGroupName: "Check IN", DisplayOrder: 2, GroupCode: 717 },
    { SubGroupCode: 889, SubGroupName: "Check In", DisplayOrder: 2, GroupCode: 718 },
    { SubGroupCode: 890, SubGroupName: "Core Skill", DisplayOrder: 15, GroupCode: 1 },
    { SubGroupCode: 891, SubGroupName: "Core Skill", DisplayOrder: 6, GroupCode: 717 },
    { SubGroupCode: 892, SubGroupName: "Core Skill", DisplayOrder: 6, GroupCode: 718 },
    { SubGroupCode: 893, SubGroupName: "Reimbursement", DisplayOrder: 1, GroupCode: 776 },
    { SubGroupCode: 894, SubGroupName: "My Contract Letter", DisplayOrder: 6, GroupCode: 701 },
    { SubGroupCode: 895, SubGroupName: "Score Moderation", DisplayOrder: 8, GroupCode: 5 },
    { SubGroupCode: 896, SubGroupName: "Score Moderation", DisplayOrder: 7, GroupCode: 718 },
    { SubGroupCode: 897, SubGroupName: "Vendor", DisplayOrder: 2, GroupCode: 713 }
  ];
  