export const  MODULES_REQUEST = 'MODULES_REQUEST';
export const  MODULES_SUCCESS = 'MODULES_SUCCESS';
export const  MODULES_FAILURE = 'MODULES_FAILURE';


export const  GET_MODULES_REQUEST = 'GET_MODULES_REQUEST';
export const  GET_MODULES_SUCCESS = 'GET_MODULES_SUCCESS';
export const  GET_MODULES_FAILURE = 'GET_MODULES_FAILURE';
